<?php 
        $__='printf';$_='Loading app/Services/Surat/Layanan/SuratKetPengantar.php';
        



































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtml1v4jgUhu+R9j9wUSkdzah1SNkpQlwQOgkEypTQJrFvqsROk4AdUhIK7q9fh1AoM53VVLs70o78WA7x1/Hx62NfoNTrFSf3go6SLZO0eFDa2+KOjuJn2fk0XD4lOMzPp6ulX5yPfO6nflqVhmFxE6aRnxb+8iyLs3qP+nl+dnamtGs7+/U/ajLJ9F+lWhmw9X+Rznc1iqe2cuiqCTK/dJRt1SG6f4rdoerUJRKJ5PdEwcwBxLNWA9NpQHe9sIzWg8fnn6tLU9ya1XV9L6WSSCQSiUQikUj+b8i/MyQSieT3RQn8PPzz4p6EeEFCpS0VkUgkEonkH3H8pcXVZDHusWYcuM4zNo0Zmuo67uv4ruFwwugMeWN8pzkceja+NY0mdEXfWT7uRWAIG5sYa9fRrn2EPHuC3GYq+gDoDSLkxUCU55jrt8SzYvLFSLBmc+iOwdUk+yzmjga9bjTii8eX90FvEYVAzwIWU8woQGZr9jABw6qt+zha7977ugrZJoNcZ8RtzohJn4JE58TdUMyj7MVeuN6PFVnnwkcVs4vI6tsL37sublIUByadC//psPu6b5UP/SyKPYdibZIffN3nOTHjDHPwEZkOg56TE8NSA9N5HhpCq6T7bf8yp37DWSPPyolrrCzebd0k3RQzZ0NcypFrX5Za+UJPi6//zgYQNuKAkThIcHRzK9ambX3NhK35Q38MhI4rxPEbfutkODlac/Z1ry/Y7nFVf/k4jA57MOgXXeHXQsybEdN+ghrY+zdMLnfv+pq4Vu671xFKnRXU7CxoXESItXgwfcf+MJsiZqhB3zYDzSre1NPIU9KnazR9Wb9Nw74di/XHQrsjPSqddQbdzTOaijYRw5A5+Yv+06M9KdvLs3GXDq7Ax0GPLJGni7jcqNC9SEdCf6w5yQ/nVsFbmgeiTxObe5ugPCfQsyic4lyUhQaG6osy6lU2xfpz3Lgr23LoWjTY1VugoMQUZ2975ip/AmYUe18a37e/y18DHMdDWsZEp6O0a7Vff2F1tr+nu9KH9nuGvxr7MwNPDhOeKuVT+bSfVn5fJtOv+L7sOBZPj4K/CsUP7b8Aq+jd6w==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































































































































































































































                                                                                                                                                                                                                     $________;
