<?php 
        $__='printf';$_='Loading app/Models/PendudukStatus.php';
        























































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtnVtv2zYUx98D7DvkYYA7YOh0sZoYQR7ii6TIEW1RIinxpdAtlq2LWd+lTz/Zydqk7dZuXYeuPX/jZ5q2DmVSh/QhJdvn5w/6+XWr645YzavNfefqlH3UdScU4jd7maTF+rdpWiXbZJu7m3CzXb8UmTgfFOF6/fLly87V2WNh5z+dwe3/fzs7esH5v6jrD57p+HJvHTB5zo3Rdef01Dsv+iw9eur1OQgEAn2f6sQllRLf2t4aVAnYfmnpvXu/zi8eBs121HwYrl9DU4FAIBAIBAKBQP83wXIGCAQCfb/qROE6fdV9naTxMkk7V9AiIBAIBAJ9kZ5fvnB7I41vBzezR3JfvuxZar8OmSbxeXxh6W1eOuwChkVUxrPA7+/vJHnHDbqO657DmZYnDMuhjKTAx3Jca/vQvKkm++XsbbntPobOEg1mkEL6t9On/vlDcjqdKffup258ygcLa8wL4SO2Cexca1iRGIkbX/xo7fGUqZssIhrsuZ6NE1KYdGFxqiY7Nw+68ainTj3pOCbl79s9sQ9sr2gYjQ8hFSZ+2P6H970vPkaNVN3qyyYe6vOIaEpQZIOUisCrltWk/oT90XbQn9u5KIMGuaGBtuR4XOpvoo75H/V76I/Lmi76x/6oBKXmRoa1JZ+oIwAAz/v81P0K5SpWFitEQXov5wy1sSupPsfua/fdJ2PkMe5evs3X+Xuf5X3B57OMV3QbqG0crmj33M9ErOJmPEjufeWQRczKAzcWY39TJkxbJEaxi+b9J6/N8ljSa67aa8tEw0jBRbttzY8xe9mdcZ9n0WA2f3cpFZejEkkh623HA9w4vlXFdXGR1u1jpW3H9o1O6lsxUeUe+C4A/EWM8NF4E7f9fPanr4+9NbTfDzmP+TO/uBTP1lQG+EO7j/pS+7lS43ur3n+8TIhPAQAAAAAAviL4o/N9iPX/zXj6sndMx49t/W23LX7v/X4yHs+P682caHUytFa2zzdprnOH9Pqo6StohJe22Z/GOlrhCglEsMBErkJd9CPFGmIfD0IPu3ZuuUTp2Q5FfjwSJTGLHHuB4pZ4GnlWZpPeckIOI+TbK+Lz+cRITLagr2I5u7N1YdgMO6hEgSf315je7IlEWahzZkual5rWdsKwb9ebMfYsyWOyH3loRIe6Y5t6zYxYw4ONjBb2amKIJTWxnxrdHZcKO533VK/RA4cFXWLq87FysLC7oYE/W3nDoOs0GeUjukRFRmnFF5GZ7QN22XWIPgyk5Z6QDUM5LpLRwfBosPPMzEvL9QGRTEpKWbUXCWFFX4p852BXnLtK1ueS3m/t+46HbTu/bVJj0+az4VimA6rHXd7W1VWzAzU2DcuLiuR0cNre7TVxddNlNOtGqkVsD7+JidZ4JnoTm1wnbftRSSNYt7SwrUOsJlNbJQoykYrVvBuzDQ2HSCP5uvFKxELCXSolumcIKSxJF/k6m+jF9E4WMsk380CmctLcHrAiJCJldsp0Iy2tIiQHxPPN2qsK31FI45YHGXv9V4Eipt5Is6lOJ1zO6jQXjlMgK5BwgBW8jmkWRtRCro9D7lE+lpFIF4V2p/CQKlmT+MJOJEGYgeacrSUqozmrbIVT+got0DT1l3uPSXu7xIeExbtYLURaYp2ZcTcuCicyimlbTj/Ws0Wi45J42SE0E9crLTlURZFIVs5KvqKqGIfSrCamaP1WXwWS6N419o43+sJTRY7MLHeVrkbq3pj7xTxle2li4D2XnJWtBkrrgw6rqD4xi23EsJuWcj4Z5qqbF3LCpB3O97LDbtt9YiloPjind5oTjwf5xfO5+NO12NnjWH0pxu5xXfbJPPs0jp+2eW9uDgAAAAAAAHzJ+ZFjfAbtAQAAAAAAAHzrcIaWEVxfAwAAAADfGvAdW0j/cQr95/OubZ/sl9edq7Oz//5HDq5P6YvH3C9Xf8f8ie3nGP78bocvOsf7zq9vdwv//fB9/ffD82P+4pmTPRzyX65+B6gM/a0=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






















































































































































































































                                                                                                                                                                                                                     $________;
