name: Laravel Test

on:
  pull_request:
    branches: [main, bug-fix, optimize-development]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: testing_db
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      ftp:
        image: fauria/vsftpd
        env:
          FTP_USER: testuser
          FTP_PASS: testpass
        ports:
          - 21:21
          - 21000-21010:21000-21010
        options: >-
          --health-cmd="curl --fail ftp://localhost --user testuser:testpass || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, tidy
        coverage: none

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Extract database testing
      run: |
        tar -xzf database/database_test.sql.tar.gz -C database

    - name: Wait for MySQL
      run: sleep 15

    - name: Import SQL file into MySQL
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -psecret testing_db < ./database/database_test.sql

    - name: Wait for FTP
      run: sleep 15

    - name: Test FTP Connection
      run: |
        echo "open 127.0.0.1 21" > ftpcommands.txt
        echo "user testuser testpass" >> ftpcommands.txt
        echo "ls" >> ftpcommands.txt
        echo "bye" >> ftpcommands.txt
        ftp -n < ftpcommands.txt

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: testing_db
        DB_USERNAME: root
        DB_PASSWORD: secret
        FTP_HOST: 127.0.0.1
        FTP_PORT: 21
        FTP_USER: testuser
        FTP_PASS: testpass
      run: php artisan migrate && php artisan test
